M7R0
I-GRAPH_THEORY=6"%&falseGE\[lep%%initGt+F$6'%-read_ObjNameG%+read_RelasG%+read_
RulesG%.read_FunctionG%1read_FuncStructsGF$F$C->8$t+F$6%%%lineG%"sG%#fdGF$F$C)>
%,Obj_StructsG7">8&-%&fopenG6%-%$catG6$%$urlGQ2/data/OBJECTS.txtF$%%READG%%TEXT
G>F1-%)readlineG6#F<?(F$"""FLF$30F1""!/-%+SearchTextG6$Q.begin_ObjectsF$F1FO>F1
FH>F1FH?(F$FLFLF$3FN/-FR6$Q,end_ObjectsF$F1FOC%>8%-%(convertG6$-%&parseG6#F1%'s
tringG@$0FinQ!F$>F97$-%#opG6#F97$FinF:>F1FH-%'fcloseGFJF$F$F$6#FO>Fint+F$6%F4%%
exprGF6F$F$C)>%-Rela_StructsGF:>F<-F>6%-FA6$FCQ4/data/RELATIONS.txtF$FEFF>F1FH?
(F$FLFLF$3FN/-FR6$Q0begin_RelationsF$F1FO>F1FH>F1FH?(F$FLFLF$3FN/-FR6$Q.end_Rel
ationsF$F1FOC%>Fin7#F]o@$/-%%nopsG6#Fin""#C$>&Fin6#FL-%$mapG6$f*6#F5F$6$%)opera
torG%&arrowGF$-F[o6$9$F`oF$F$F$Fer>Fdp7$-Fgo6#FdpFin>F1FHF[pF$F$F$6#FO>F<t+F$6&
F6%+read_1RuleGF4%'thutucGF$F$C*>Fint+F$6*%%loaiG%%tensG%&kieusG%%ten1G%#n1G%&k
ieu1G%&gt_klG%"kGF$F$C->F1Fco>FinF:>F<F:>8*7$<"F`u>T#Fco>T%-FI6#T'?(F$FLFLF$330
FduFO/-FR6$Q+begin_ruleF$FduFO/-FR6$Q*end_rulesF$FduFO>FduFeu@$2FOFav-%'RETURNG
6#%%NULLG>FduFeu?(F$FLFLF$3F[v/-FR6$Q)end_ruleF$FduFOC$@%2FO-FR6$Q*kind_ruleF$F
du>F1-%$rhsG6#-F^o6#FduC$>8+-FR6$Q":F$Fdu@*2FO-FR6$Q0hypothesis_partF$FduC&>&F^
uFfr-%*substringG6$Fdu;,&F`xFLFLFL-%'lengthGF]x>FduFeu?(F$FLFLF$3F[v/-FR6$Q4end
_hypothesis_partF$FduFOC$>F[y-FA6$F[yFdu>FduFeu>F[y-F^o6#F[y2FO-FR6$Q*goal_part
F$FduC&>&F^u6#FbrF\y>FduFeu?(F$FLFLF$3F[v/-FR6$Q.end_goal_partF$FduFOC$>Fhz-FA6
$FhzFdu>FduFeu>Fhz-F^o6#Fhz2FO-FR6$Q%procF$Fdu>Fbu-F^o6#-F]y6$Fdu;,&FaxFLFLFLFa
y2FOF`xC'>8'7#-F^o6#-F]y6$Fdu;FL,&F`xFL!""FL>8(-F`r6#Fg\l>8)-F[o6$-F^o6#F\yF`o>
Fin7$-FgoFar-FgoFc]l>F<7$-FgoFJ-%"$G6$Fe]lFa]l>FduFeu@$0%$tenGF:@%/F1Q6GRAPH_VE
RTEX_IN_GRAPHF$>%0RuleEqs_StructsG7$-Fgo6#F\_l7'F1FinF<F^uFbu>%-Rule_StructsG7$
-Fgo6#Fb_lF`_lF$F$6(F\tFg\lF4F<F6F16#FO>Fb_lF:>F\_lF:>F1-F>6%-FA6$FCQ0/data/RUL
ES.txtF$FEFF>F<-FIF_o?(F$FLFLF$30F<FO/-FR6$Q,begin_rulesF$F<FO>F<Fa`l?(F$FLFLF$
3Fd`l/-FR6$FcvF<FO-FinF$-F\pF_oF$F$F$6#FO>Fg\lt+F$6*F6F4F5%"jG%$triGFg^l%%bienG
%#tcGF$F$C)>%*Fun_NamesGF:>F1-F>6%-FA6$FCQ4/data/FUNCTIONS.txtF$FEFF>FinFa`l?(F
$FLFLF$30FinFO/-FR6$Q0begin_functionsF$FinFO>FinFa`l>FinFa`l?(F$FLFLF$3Febl/-FR
6$Q.end_functionsF$FinFOC(>Fa]l-F]y6$Fin;FL,&-FR6$Q"~F$FinFLF_]lFL>Fe]l-F]y6$Fi
n;,&FhclFLFLFL,&-FR6$Q"(F$FinFLF_]lFL>F^u-Fhr6$f*F[sF$F\sF$F_sF$F$F$7#-F^o6#-F]
y6$Fin;Fadl-FR6$Q")F$Fin>F`x-F^o6#-F]y6$Fin;-FR6$Q"|frF$Fin-FR6$Q"|hrF$Fin>F[bl
7$-Fgo6#F[bl7&Fa]lFe]lF^uF`x>FinFa`lF`alF$F$F$6#FO>Fa]lt+F$62F6%*read_FuncGF4%"
tG%%InitG%)ReadNameG%*ReadBaseOG%+ReadReturnG%)ReadProcG%)ReadPropG%)ReadFuncG%
&NameFG%'BaseOFG%)ReturnOFG%&ProcFG%&PropFGF$F$C/>Fa]lt+F$F$F$F$C(>FbuFco>Fdu7$
F:F:>FguF:>T)Fco>T+F:>T-FcoF$F$6.F`gl8/Fagl80Fbgl81Fcgl82Fdgl83FhflFg\l6#FO>Fe]
lt+F$6$FhtF5F$F$C&>F1-FR6$FcxFbu>Fin-F]y6$Fbu;,&F1FLFLFL-Fby6#Fbu>Fdu-F[o6$-F^o
FarF`o>Fgu-F]y6$Fdu;-FR6$FcdlFduFayF$F$6(F4F<F`glFdhlFhflFg\l6#FO>F^ut+F$6(Fht%
$lstGF5%%nameG%&listOG%&listTGF$F$C'>Fa]lF:>Fe]lF:>Fbu-FIF]x?(F$FLFLF$30FbuFO/-
FR6$Q'returnF$FbuFOC%>F1F_il@$2FOF1C'>Fin7#-F^o6#-F]y6$Fbu;FL,&F1FLF_]lFL>Fa]l7
$-Fgo6#Fa]lF\^l>F<Fbil>Fg\l-F[o6$-F^oFJF`o>Fe]l7$-Fgo6#Fe]l-Fb^l6$Fg\lF_r>FbuF_
[m>Fgu7$Fa]lFe]lF$F$6(F4F<F6F1FaglFehl6#FO>F`xt+F$6%FhtF5FhflF$F$C$>F1F_il@$Fj[
mC%>F<-F^o6#-F]y6$Fbu;,&Fd[mFL""'FLFc\m>Fin-F[o6$-F^o6#FbilF`o>Fdu7$F<FinF$F$6&
F4F<FbglFfhl6#FO>8,t+F$F$F$F$C%>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$Q)end_procF$FbuFOC$
>Fgu-FA6$FguFbu>FbuF_[m>Fgu-FA6&F\\lF^hlFguQ%end:F$F$F$6*F4F<F6F1FcglFghlFhflFg
\l6#FO>8-t+F$6#%#exGF$F$C$>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$Q/end_propertiesF$FbuFOC
%>F1-F^oFgil@$-%&evalbG6#0F1Fjv>Fgu7$-FgoFfuF1>FbuF_[mF$F$6(F4F<F6F1FdglFhhl6#F
O>8.t+F$F$F$F$C)-FbuF$>FduFeu?(F$FLFLF$33F[v/-FR6$Q/begin_functionF$FduFO/-FR6$
FaclFduFO>FduFeu@$2FOF_cmFgv?(F$FLFLF$3F[v/-FR6$Q-end_functionF$FduFOC$@*2FOF[c
mC%-F^hlF$-F`hlF$\2FO-FR6$Ff[mFdu-FbhlF$2FO-FR6$Q+begin_procF$Fdu-T/F$2FO-FR6$Q
+propertiesF$Fdu-T1F$>FduFeu>FduFeu@$0T3Fco>%-Func_StructsG7$-Fgo6#Fgem7'FeemT5
T7T9T;F$F$6<FiflFa]lF4F<F6F1FjflFe]lF[glF^uF\glF`xF]glFa_mF^glFg`mF`glFdhlFaglF
ehlFbglFfhlFcglFghlFdglFhhl6#FO>FgemF:>F1-F>6%-FA6$FCQ?/data/DEFINE-FUNCTIONS-t
mp.txtF$FEFF>F<Fa`l?(F$FLFLF$3Fd`l/-FR6$FiblF<FO>F<Fa`l?(F$FLFLF$3Fd`l/-FR6$Fac
lF<FO-FbbmF$F`alF$F$F$6#FO>%.O_Hypos_RulesGF:-F1F$F_al-F<F$-Fg\lF$-Fa]lF$F$6*FC
F9FdpFb_lF\_lF[blFgemFhgmF$6#FO%.Deduce_ObjectGt+6$%"dG%%GoalG60%.ObjStructTemp
G%(thaytheG%$FK2G%$FK3G%%FK45G%0Deduce_ObjRulesG%/Deduce_ObjPropG%6Deduce_OCons
tructRelaG%0Deduce_ObjRela1G%1Deduce_ObjRela21G%1Deduce_ObjRela22G%0Deduce_ObjR
ela3G%/Deduce_ObjFuncG%(replaceGF$F$C?>F1-%2ObjStruct_ReplaceG6#Fas>Ffhlt+F$F$F
$F$C&>Fbu-%.Find_VarUnifyG6#<#-Fgo6#&%+Fact_KindsGFiz>Fdu-%3Replace_StructNameG
6#-%%subsG6$FbuF_jm>Fgu-Ffjm6#-Fijm6$Fbu<#-Fgo6#&Fcjm6#""$>F^hl-Ffjm6#-Fijm6$Fb
u<$-Fgo6#&Fcjm6#""%-Fgo6#&Fcjm6#""&F$F$6*FfhmFinFghmF<FhhmFg\lFihmFa]l6#FO>F^ut
+F$6%%%propGFht%%newsGF$F$C&>F<F`u?&F1&Fbu6#Ff^m%%trueGC$>Fin-%*Kind_FactGF_o@$
331FLFin1Fin"#64-%*Unify_In1G6$F1&%*Fact_KindGFarC$>F<<$F`^lF1>&FcjmFar7$-Fgo6#
Fg^nF1@$0F<F`uC$>%(FactSetG-%&unionG6$F__nF<>%$SolG7$-Fgo6#Fd_n7&Q/Deduce_ObjPr
opF$F:F`uF<>%)TestPropG<$-Fgo6#F[`nT&F$F$6&FehmF1FbhmFas6#FO>F`xt+F$6)%"iG%"fGF
ap%$theG%%btheGFht%%varsGF$F$C%>Fg\lF`u>Fa]lF`u?&Fin&FbuFd\nFb]nC'@$-%'memberG6
$7$F_`nFin%(TestOCRGF`dm>F^u-%)Set_VarsGFar?&F1F^uFb]n@$3-%%typeG6$F1%)function
G0-Fgo6$FOF1%".G>F^u-Fa_n6$-%&minusG6$F^u<#F1-Fhan6#-FgoF_o?&F1F^uFb]n@$33333F
\bn/FabnFcbn-Fban6%-Fgo6$FLF1&&FbuFizFfr.Fe]l-F]bn6$-F^o6#&-%*ObjStructG6#&&F[d
nFizF`]mFfr%(indexedG-Fban6$FhcnFgu4-F]bn6$-%+Get_ValuesG6#FhcnF`oC$>Fa]l<$Ff\m
/FhcnF]en@&/-Fgo6$FbrF1%"xG>Fg\l<$F]^l/F1&F]enFfr/Ffen%"yG>Fg\l<$F]^l/F1&F]enFi
z@$0Fg\lF`uC$>F<-Fijm6$Fg\lFin@$/-Fhan6#-FjwFJF`uC$>Fe]l-Ff]nFJ@$331FLFe]l1Fe]l
F\^n4-F_^n6$F<F__nC'>&FcjmF`]m7$-Fgo6#F[hnF<>F__n-Fa_n6$F__n<#F<>Fd_n7$Ff_n7&Q6
Deduce_OConstructRelaF$7#FinFa]lFbhn>Fean-Fa_n6$Fean<#Fdan>%%flagGFb]nF$F$6(Feh
mF1FbhmFasFghmF<6#FO>Fa_mt+F$6*Ff`nFi`n%%factGFapF\]nFj`mFhtFhflF$F$?&F1&Fbu6#"
"(Fb]nC%@$-Fban6$7$F_`nF1FeanF`dm>Fin-Fhbn6$&F1Fd[nFgu@$53/&F1FizFL/F_rFL3/Fejn
FO/Fin&F1Fd\nC%>Fg\l-Fijm6$F^hl&F1Fa]n>Fa]l-%(MySolveG6%Fg\lFinFL@$0Fa]lF`uC'>F
ean-Fa_n6$Fean<#F\jn?&Fe]l&Fa]lFfrFb]nC$>F^u-Ff]nF`]m@$3331FLF^u1F^uF\^n/-FhamF
`]mF%4-F_^n6$Fe]lF__nC$>&Fcjm6#F^u7$-Fgo6#F]]oFe]l>F__n-Fa_n6$F__n<#Fe]l>F`x-Fh
bn6$F`jnFin>Fd_n7$Ff_n7&Q0Deduce_ObjRela1F$F1<#-%$seqG6$/&F`x6#Fe`n-F^en6#Fb^o/
Fe`n;FL-F`r6#F`xF\\o>F]inFb]nF$F$6*FehmF1FbhmFasFghmF<FhhmFg\l6#FO>Fg`mt+F$Fbin
F$F$?&F1FeinFb]nC%@$FjinF`dm>FinF^jn@$F^r?&F<-Fhbn6$-Fhbn6$F^hl%%DF53G%%DF43GFb
]n@$/-Fhbn6$-FhanFJFguFinC&>Fg\l-Fijm6$F`hl<$F_[oF<>Fa]lF`u@$/Fb]lFbr>Fa]lFa[o@
$Fe[oC'>FeanFh[o?&Fe]lF\\oFb]nC$>F^uF_\o@$Fa\oC$>F]]oF_]o>F__nFc]o>F`x-Fhbn6$-F
a_n6$F`jnF_`oFin>Fd_n7$Ff_n7&Q1Deduce_ObjRela21F$F1-Fa_n6$FbhnF]^oF\\o>F]inFb]n
F$F$6,FehmF1FbhmFasFghmF<FihmFa]lFhhmFg\l6#FO>Fbbmt+F$6.Ff`nFi`n%&vars1G%&vars2
GFcin%&fact1G%&fact2GFapF\]nFj`mFhtFhflF$F$?&F1FeinFb]nC%@$FjinF`dm>FinF^jn@$/F
_rFe[n?&Fa]l-&%)combinatG6#%'chooseG6$Fe_oFbrFb]nC'>Fe]lF\\o>F^u&Fa]lFiz>F<-Fhb
n6$-FhanF`]mFgu>Fg\l-Fhbn6$-FhanF^]oFgu@$333-F_^n6$F<Fin2FL-F`rFJ-F_^nFhfn2FLFb
]lC&>F`x-Fijm6$F`hl<%F_[oFe]lF^u>Fa_mF`u@$/Fh^oFe[n>Fa_m-Fb[o6%F`xFinFL@$0Fa_mF
`uC'>FeanFh[o?&Fg`m&Fa_mFfrFb]nC$>Fbbm-Ff]n6#Fg`m@$3331FLFbbm1FbbmF\^n/-FhamF_f
oF%4-F_^n6$Fg`mF__nC$>&Fcjm6#Fbbm7$-Fgo6#F]goFg`m>F__n-Fa_n6$F__n<#Fg`m>Fdhl-Fh
bn6$-Fa_n6$-Fa_n6$F`jnF\doF`doFin>Fd_n7$Ff_n7&Q1Deduce_ObjRela22F$F1-Fa_n6$Fa]l
<#-F_^o6$/&FdhlFc^o-F^en6#Fgho/Fe`n;FL-F`r6#FdhlF[fo>F]inFb]nF$F$F_bo6#FO>Fdhlt
+F$6*Ff`nFi`nFap%&expr1GF\]nFj`mFhtFcinF$F$?&F1FeinFb]nC%@$FjinF`dm>F<-Fijm6$Fg
uF_[o?&F`xFe_oFb]nC%>Fa]lF`u@&3Fdjn5/-Fhbn6$-FhanFi^oF`jnF`u/-Fhbn6$F`jnFcjoF`u
C'>Fin<#&-%*intersectGFbjoFfr>Fg\l-Fb[o6%F<FinFL@$/Fg\lF`uF`dm>Fa]l<#-Fijm6$&Fg
\lFfrF`x-%&printGFg\m33Fhjn/-Fhbn6$FjjnFcjoF`uF_joC%>Fg\l-Fb[o6%F<FjjnFL@$Fa[pF
`dm>Fa]lFc[p@$Fe[oC%>FeanFh[o?&Fe]lFa]lFb]nC$>F^uF_\o@$3Fc\oFh\oC%>F]]oF_]o>F__
nFc]o>F]inFb]n>Fd_n7$Ff_n7&Q0Deduce_ObjRela3F$7$F1F`xF`uFa]lF$F$6*FehmF1FbhmFas
FhhmFg\lFihmFa]l6#FO>Fehlt+F$F$F$F$F$F$F$F$6#FO>Fe]lt+F$6)%%ruleGF\]nFj`mFhtFhf
l%&trihpG%'hamphuGF$F$C$>F^ut+F$6&%"hG%#ttG%$doiGFealF$F$C)>Fin-Fgo6$FO-Fjw6#F^
an>F<7#-Fgo6#F[_p?(Fg\lFLFLFhdoFb]n@$-F_^n6$&F<Fc]l7$F`jm-Fgo6#&FcjmFfin>Fe_p-F
^en6#Fe_p>F1-F^o6#-FA6&-F[o6$-%$lhsGF\_pF`oQ#=(F$-F[o6$-Fin6#F`^lF`oF`el>FduFe]
n@$3/FduFe[n4-F_^n6$F1%#FNGC&>&FcjmF]x7$-Fgo6#FeapF1>Fbjm7$F`jm-Fe`pF_o>%$DF3G-
Fa_n6$F]bpFjbn>F__n-Fa_n6$F__n<$F[bpF1OFcbpF$6#F]bp6&F]^pF1FhtFg\l6#FO?&F1&Fbu6
#"")Fb]nC%@$-Fban6$F\jn%'TestORGF`dm>Fin-%*ApplyRuleG6$F1F__n@$0FinF`uC)>F`cp-F
a_n6$F`cpFj[o?&F<FinFb]nC$>Fg\lF`gn@$331FLFg\l1Fg\lF\^nFfgnC$>&FcjmFc]l7$-Fgo6#
FedpF<>F__nF`hn>Fe]lF`u@$0FjjnFco>Fe]l-F^uF$?&Fa]l<$Fa[n-Fgo6#&FcjmFjbpFb]n@$-F
_^n6$-Fe`pFg\m&&F1F_\nFfr>Fhep-%,Minus_UnifyG6$-Fa_n6$Fhep<#Fa]l<#Fgep>Fd_n7$Ff
_n7&Q0Deduce_ObjRulesF$F1Fhep-Fa_n6$FinFe]l>F]inFb]nF$F$F``n6#FO-FfhlF$@$4-Fban
6$FasF[`nC%F^ep-%.Deduce_From3sGF$@$3F]in-%*Test_GoalG6$9%F__nOF$Fjfp@$43/-%*ty
pe_OnetGFgimQ%DOANF$4%(flagObjGC&-F`xF$F`gp@$FcgpOF$Fjfp-Fe]lF$F`gp@$FcgpOF$Fjf
p-Fa_mF$F`gp@$FcgpOF$-Fg`mF$F`gp@$FcgpOF$FjfpFegmF`gp@$FcgpOF$FjfpF$6)FcjmF__nF
d_nF]inF`cpFeanF[`nF$6#Fbr%.Output_ResultGt+6#Fchm6(%&factsGFhfl%&valueG%)Solut
ionGFe`nFealF$F$C$>Fg\lt+F$6&%)goalvarsG%'SolnewG%%StepGFe`nF$F$C&>F1<#T$>FinF:
?(Fg\l-F`rFg_nF_]lFLFb]nC$>F<&Fd_nFc]l@$50-%0Intersect_UnifyG6$&F<F_\nF1F`u0-F
\[pF`[qF`uC%>Fa[q-Fa_n6$F^[qFc[q@$30&F<FfrQ.Deduce_From3sF$0F[\qQ.Deduce_From8s
F$>Fin7$F<F\^l>F1-%,Union_UnifyG6$-F\fp6$F1Fa[q&F<Fd[nOFinF$F$6$FchmFas6#FO@%4-
Fegp6$FasF__n-%'printfG6$QB|+~~Rat~tiec~%a~khong~giai~duoc~|+|+F$FasC(>F<-F^enF
gim@%-F]bn6$F<%$setGC$-F`]q6#QP|+~~~~***K&#7870;T~QU&#7842;~C&#7846;N~T|gwM~L|[
w:~|+F$?&Fa]lF<Fb]n-F`]q6%Q*~%a~=~%a|+F$FasFa]l-F`]q6%QX|+~~~~***K&#7870;T~QU&#
7842;~C&#7846;N~T|gwM~L|[w:~%a~=~%a|+|+F$FasF<-F`]q6#QQ|+*****~L&#7900;I~GI&#78
42;I~NH&#431;~SAU:~*****|+F$?&FinFd_nFb]n-F`]q6$Q(~**~%a|+F$Fin-F`]q6#Q_p|+|+**
***~L&#7900;I~GI&#7842;I~CHI~TI&#7870;T~C&#7910;A~B|[wI~TO|\wN~NH&#431;~SAU:~**
***~|+F$?&Fe]lF[hmFb]n-F`]q6$Q)~**~%a~|+F$Fe]lF$6$FcjmFd_nF$6#FL%,Has_ElementGt
+Fi`mFc^oF$F$C$?&F1FasFb]n@$-%+Is_ElementGF_o-Fhv6#Fb]n-Fhv6#F%F$F$F$6#FL%/Dete
rmine_GoalGt+Feip6*Fifl%'ValuesG%%funcG%+funcstructGFgip%$SetG%#dsG%(founddsGF$
F$C%>F1t+F$F$F$F$C%>%(ObjsNewGF:>%*OTypesNewGF:>%)FactsNewGF:F$F$F$6#FOFigm@%-%
,Is_FunctionGFgimC$?&F^u7#-FgoFgimFb]nC$-Fh[p6$Q3------------------F$F^u@%4-Feg
p6$F^uF__nC$-Fa`qF^]o@%FabqC$>F`xF%[>F`xFb]n>F`xFb]n@$F`xC)>Fin-F^en6#Fjaq>F<F]
hp>Fg\l-%0Find_FuncStructGFJ>Fa]l-%-Compute_FuncG6%Fg\lFjaqFin>%&TestFG-Fa_n6$F
jcq<#7$F<Fjaq>Fe]l-%/Classify_FactsG6#7#Ff\m>Fd_n7$Ff_n7&Q/Determine_GoalF$F<<#
-F_^o6$/&F[bqFc^o-F^en6#F\eq/Fe`n;FL-F`rFgimFe]l-%*DetermineGFgimF$6'FjcqFd_nF_
aqFaaqFcaqF$6#FL%4Odinary_Hypos_RulesGt+F$6%%3Odinary_Hypos_RuleG%'tenhamG%%Rul
eGF$F$C$>F1t+6#F]^p6)Fcin%'o_factGFf`nFfhm%)lhs_factG%)o_numberG%&vitriGF$F$C'>
FinF:>Fe]lF:>Fg\l<#-F_^o6$/&&FasFizFc^o&&FasFd[nFc^o/Fe`n;FL-F`r6#F^gq?&F1&&Fas
F_\nFfrFb]n@&3-F]bn6$F1%%listG-F]bn6$&F1FfrF`oC'>F1-Fijm6$Fg\lF1?(F<FLFL-F`rF_o
Fb]n@&-F]bn6$&F1FJFgdn>F1-Fijm6$/Fihq-%)NameTypeG6#FihqF13-F]bn6$FihqF_bn0-Fgo6
$FOFihqFcbn>F1-Fijm6$/Fihq-F[o6$FeiqF`oF1>F1-%0Is_RelationTypeG6$F1FL>F^u-%*Bel
ong_InG6$F1Fin@%/F^uF_]lC$>Fin7$F\^lF1>Fe]l7$F_]mFL>&Fe]lF^]o,&F][rFLFLFL33-F]b
n6$F1%"=G-Fban6$-F[o6$-Fgo6$FO-FjwF_oF`oFbu4-Fban6$-F[o6$-Fgo6$FOF[bpF`oFbuC(>F
1Fbhq>Fa]lF[bp>F1-%1Find_OdinaryFuncG6#Fj[r>F1/Fa]lF1>F^uFbjq@%FfjqC$>FinFijq>F
e]lF[[r>F][rF^[rO7$FinFe]lF$F$6$FjeqFin6#FL@$/FhgmF:C$>Fin7#-F_^o6$&&F[blFc^oFi
z/Fe`n;FL-F`rF`fl?&F<Fb_lFb]n>Fhgm7$-Fgo6#Fhgm-F1FJF$Fe^rF$6#FOFegpt+6$Fchm%&Fa
ctsGF$F$F$O-F_^n6$FasFggpF$F$F$6#Fbr%)RelaPropGt+6$'%&slistGF\hq'F[]nF`o6$%&nli
stGFe`nF$F$C%>F1-Fhr6$f*F[sF$F\sF$-F_iqFgimF$F$F$Fas?(FinFLFL-F`rFesFb]n@$/F1&&
FdpFarFfr@'/9#FL-Fhv6#&Fb`rFiz-Fban6$FggpFh`rF\`qF^`q@%Fd`r-Fhv6#F`uF^`qF$F$F$6
#Fbr%)ReadExerGt+6#'FCF`o6*F4F6%-read_objectsG%+read_factsG%+read_funcsG%+read_
goalsG%,read_paramsG%'updateGF$F$C.>F`xt+6#%(ex_varsG6%Fi`nFe`nFealF$F$C$>F1-Fh
bn6$Fas-Fa_n6$-Fa_n6$-F[o6$%(ObjectsGFi]q-F[o6$%'OAttrsGFi]q-F[o6$%&FuncsGFi]q?
&FinF1Fb]n@)-FgaqFarC&@$/-F^hpFarQ&type?F$F`dm>F`cr7$-Fgo6#F`crFin>%+Func_Types
G7$-Fgo6#F^drFgcr?&F<7#F\^lFb]n-Fbu6#F_`o3-%5ValidStructName_OnetGFar-F_^n6$<#F
\^lFjbrC%@$FfcrF`dm>%*Obj_TypesG7$-Fgo6#F_erFgcr>Fjbr7$-Fgo6#FjbrFin3333-F]bn6$
FinF_bn/-Fgo6$FOFinFcbn4-F_^n6$-Fgo6$FLFinFjbr-Fhdr6#Fcfr-F_^n6$<#-FgoFffrFjbrC
'@$FfcrF`dm>F_er7$Faer-F^hpFffr>Fjbr7$FeerFcfr>F]cr7$-Fgo6#F]crFin>%,OAttr_Type
sG7$-Fgo6#FggrFgcrC%@$FfcrF`dm>F]crFcgr>FggrFhgrF$F$6$FiarF`x6#FL>F^ut+F$F$F$F$
C$>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$Q/end_parametersF$FbuFOC$>%'ParamsG-Fa_n6$F]ir<#
Feam>FbuF_[mF$F$6&F4F1F6Fin6#FO>F<t+F$6&FhtFdtFftFetF$F$C$>FbuF_[m?(F$FLFLF$3Fb
[m/-FR6$Q,end_objectsF$FbuFOC%>F1F_il@$Fj[mC'>FinF]\m>Fg\lF_r>F<Fh^m>Fjbr7$Feer
F\^l>F_er7$Faer-Fb^l6$F<Fg\l>FbuF_[mF$F$Fbir6#FO>Fg\lt+F$6&FhtF5F^brFj`mF$F$C&>
FbuF_[m>F<F`u?(F$FLFLF$3Fb[m/-FR6$Q*end_factsF$FbuFOC%>Fin7#Feam?&Fg\lFinFb]nC$
>F1-Ff]nFc]l@$331FLF11F1F\^n4-F_^n6$Fg\lFj^rC%>Fj^r<$-Fgo6#Fj^rFg\l>&FcjmF_o7$-
Fgo6#F_]sFg\l>F<-Fa_n6$F<-FhanFc]l>FbuF_[m-FguFJF$F$6(F4F1F6FinFiarF`x6#FO>Fa]l
t+F$F`[sF$F$C&>FbuF_[m>F<F`u?(F$FLFLF$3Fb[m/-FR6$FaclFbuFOC%>FinF\\s?&Fg\lFinFb
]nC$>F1F`\s@$3Fc\s4-F_^n6$Fg\l%*FunctionsGC%>F__s<$-Fgo6#F__sFg\l>F_]sF`]s>F<Fd
]s>FbuF_[mFh]sF$F$Fi]s6#FO>Fe]lt+F$6&F5Fj`mF^brFhtF$F$C&>FbuF_[m>F<F`u?(F$FLFLF
$3Fb[m/-FR6$Q)end_goalF$FbuFOC%>F1F\\s?&FinF1Fb]nC$>Fg\l-Ff]nFar@$5F`dp3-Fban6$
FinF]ir4-F_^n6$Fin%&GoalsGC$>Fcas7$-Fgo6#FcasFin>F<-Fa_n6$F<Fgan>FbuF_[mFh]sF$F
$Fi]s6#FO-%+Reset_OnetGF$>Fin-F>6%FasFEFF>F1-FIFar?(F$FLFLF$3FN/-FR6$Q/begin_ex
erciseF$F1FO>F1Fdbs?(F$FLFLF$3FN/-FR6$Q-end_exerciseF$F1FOC,>F1Fdbs?(F$FLFLF$33
FN/-FR6$Q1begin_hypothesisF$F1FOF^cs>F1Fdbs@$2FOF_csC$-F\pFarOFjv>F1Fdbs?(F$FLF
LF$3FN/-FR6$Q/end_hypothesisF$F1FOC$@*2FO-FR6$Q,parameters:F$F1F^ep2FO-FR6$Q)ob
jects:F$F1Fjgm2FO-FR6$Q'facts:F$F1F[hm2FO-FR6$Q+functions:F$F1F\hm>F1Fdbs>%&Hyp
osG-Fa_n6$Fj^rF__s>F1Fdbs?(F$FLFLF$3FN/-FR6$Q+begin_goalF$F1FO>F1FdbsFfhp>F1Fdb
sF_dsF$6.F\fsFcasF]irFjbrF_erFj^rFcjmF]crFggrF`crF^drF__sF$6#FL%.Deduce_From9sG
t+F$6#%&fact9GF$F$C$?&F1&Fcjm6#""*Fb]n@$34-Fban6$F1%$DF9G-%(SubListG6$7#-FgoFh
\rFbjmC$-%-Deduce_From9GF_o>Fhgs-Fa_n6$FhgsFjbnO7$FcjmFd_nF$6$FcjmFhgsF$6#FO%0D
educe_From983sGt+F$6&F]gs%%tempG%&fact3G%&fact8GF$F$C$?&F1F`gsFb]n@$FegsC$?&F<F
c[nFb]n@$3-%+Unify_FactG6$F[bp-Fe`pFJ4-Ffis6$Fj[rFcepC)>Fin-Fijm6$/FhisFj[rF<>F
cep7$FaepFin>F__n-Fa_n6$F__n<#Fin>Fd_n7$Ff_n7&Q+deduce~983F$F:<$F1F<Ffjs>FhgsFb
hs>F]inFb]nFibq@$Fegs?&Fg\lFcepFb]n@$3-Ffis6$Fj[r-Fe`pFc]l4-Ffis6$F[bpFc[nC)>Fi
n-Fijm6$/Fd[tF[bpFg\l>Fc[n7$Fa[nFin>F__nFdjs>Fd_n7$Ff_n7&FjjsF:<$F1Fg\lFfjs>Fhg
sFbhs>F]inFb]nFibqOFehsF$6'FcjmF]inF__nFd_nFhgsF$6#FOFcjqt+6$FcinFj^r6#Ff`nF$F$
C$?(F1FLFL-F`r6#FggpFb]n@$/&FggpF_oFasOF1OF_]lF$F$F$6#FbrF`hst+F\gs6+Fd`qFe`nFe
`qFhtFf`qFgipFg`q%'gtbienG%$tamGF$F$C%>F1-F^en6#7#-Fgo6#-FjwFgim>F<-F^hpF`^t@$4
-Fban6$7$F<F^^tFjcqC)>Fa]lFccq>Fe]l-Fgcq6&Fa]l-%+Replace_DSG6$F^^tFg\qF1-Fe`pFg
im>Fjcq-Fa_n6$Fjcq<#Fh^t>F^u-Fadq6#7#F_]m>F`xF`u?&FinF^^tFb]n@%5/FgcrQ+DUONGTHA
NGF$/FgcrF_hpC$>Fa_m-F^o6#-FA6$-F[o6$FinF`oQ#.fF$>F`x-Fa_n6$F`x<#/Fa_m-F^enFar>
F`x-Fa_n6$F`x<#/FinF_at>Fd_n7$Ff_n7&Q-Deduce_From9F$7#F<-Fa_n6$<#FasF`xF^uF$6%F
cjmFjcqFd_nF$6#FLFhdrt+6#Fhjl6#%$Sn1GF$F$C'@$4-F]bn6$FasFgdnF^`q@$4-Fban6$F\`r-
Fhr6$f*6#FhenF$F\sF$&FasFfrF$F$F$F9F^`q>F1-F^o6#&-Fcdn6#F\`rFfr@$54-F]bn6$F1Fgd
n0FaeqFehqF^`qF\`qF$F$F$6#FLF_[qt+6$%%AsetG%%BsetG6$Fcin%%CsetGF$F$C%>FinF`u?&F
1FasFb]n@$-F_^n6$F1Fggp>Fin<$F\^lF1OFinF$F$F$6#Fbr%/Classify_RulesGt+F[s6+%"rG%
+Rules_TempG%&fact6GFe`n%+Fact_HyposG%(o_hyposG%(o_rulesGFdfq%'cothoaGF$F$C(-Ff
eqF$>Fe]l-%.Odinary_HyposGF$>FinF:>F<F`u?(F1FLFL-F`rFe_lFb]n@$3-Fban6$&&Fb_lF_o
Ffr7$F[bqF`^l-Fjgs6$&FfftFd[nF_erC&>F^u&FhgmF_o>Fa_mFb]n?(Fg\lFLFL-F`rFazFb]nC$
>F`x-Fcjq6$&F[yFc]l&Fe]lFfr@%/F`xF_]lC$>Fa_mF%Fibq@$2&&Fe]lFizFi^o&FhzFc]lC$>Fa
_mF%Fibq@$Fa_m@%5/FeftQ&GRAPHF$/FeftQ&logicF$>Fin7$FfftF\^l>Fin7$F\^lFfftOFinF$
6&Fb_lF_erFcjmFhgmF$6#FL%-Deduce_From8Gt+6#F]is6$%&fact7GFe`nF$F$C%>F1Fa_t@%4-F
_^n6$F1Fi_pC%>Fi_p7$Fg_pF1>F__n-Fa_n6$F__nFjbn>Fd_n7$Ff_n7&F^\qF:F\btFjbn?(FinF
LFLFgjpFb]n@$3/&&Fd_nFarFfrF^\q/&FijtF_\nFjbn>&FijtFd[n-Fa_n6$F][uF\bt>F]inFb]n
F$6&FcjmF__nFd_nF]inF$6#FLF\fpt+F_dtF$F$F$O-Fhbn6$Fas-F_[qF]_rF$F$F$6#Fbr%0Dete
rmine_GoalsGt+F$6&FiflFchmFhfl%&time1GF$F$C(>Fg\l-%%timeGF$>F1t+F$F$F$F$C1>F__n
F\fs>Fd_nF:>F]bpF`u>Fj_oF`u>Fi_oF`u>%%DF45GF`u>%$DF8GF`u>FhgsF`u>FjcqF`u>%&Test
RGF`u>F`cpF`u>FeanF`u>F[`nF`u>%&chisoGFL>FahpF%F$F$F$6#FOFigm?&F<FcasFb]n@$333-
F]bn6$F<F_bn/-Fgo6$FOF<Fcbn/-F_iq6#-Fgo6$FLF<F_hp/-Fgo6$FbrF<%"aGC$>FahpFb]nFib
q?&FinFcasFb]n@%-Fegp6$FinF__nC$-F`]q6#Q=~***Bai~toan~khong~can~giai|+F$-FcipFa
rC$-Fa`qFarFe_u-%'lprintG6$%+Total~TimeG,&F_\uFLFg\lF_]lF$62F__nFjcqF`]uF`cpFea
nFd_nFcasF]bpFj_oFi_oFj\uFhgsF\]uF[`nFe]uFahpF$6#FOFfimt+6#Fbhm6&%'OSTempGFe`nF
htFfhmF$F$C(>F1-Fcdn6#F]hp>F1-Fijm6%/Q'ObjectF$Fas-F_^o6$/&&F`jnFfrFar-Fcbn6$Fa
sF_au/Fin;FL-F`r6#F`auF1>Fg\lF`u@%FfbtC&>F1-Fijm6$-F_^o6$/&7#-Fgo6#-F^o6#F_hqFa
r&FjaqFar/Fin;FL-F`rF`cqF1>&F`jnFiz-Fhr6$f*F[sF$F\sF$-F[o6$-Fijm6$-F_^o6$/&7#-F
go6#-F^o6#&FguFfrF]x&7#-Fgo6#FdjpF]x/Fdu;FL-F`r6#F^du-F^oFgimF`oF$F$6(FbhmFasFe
`nFinFb`uF1F[cu>F_hq-F[o6$-Fijm6$F]buFdbuF`o?(F<FLFLFeauFb]n@$2FO-FR6$Q$GocF$-F
[o6$&F`auFJF`o>Fg\l<$F]^l/Fdeu-Fcbn6$Fas-F^o6#-FA6$Faeu&-Fgo6#-F^o6#&F[cuFJFiz?
&Fin&FcjmFfrFb]n@$3/FerFas-F]bn6$-F^o6#&FinFizFgdnC&>F1-Fijm6$-F_^o6$/&Fabu6#Fe
al&7#-Fgo6#F[guFfgu/Feal;FL-F`r6#FhguF1>F[cu-Fhr6$f*F[sF$F\sF$-F[o6$-Fijm6$-F_^
o6$/&7#-Fgo6#-F^o6#&FduFfrFfgu&7#-Fgo6#-F^o6#F[dnFfgu/Feal;FL-F`r6#FbiuFeduF`oF
$F$6&Fe`nFinFb`uF1F[cu>F_hq-F[o6$-Fijm6$FbguFdbuF`o?(F<FLFLFeauFb]n@$F^eu>Fg\lF
feu>F1FbhqOF1F$F$F$6#FLFdcqt+6#Fe`qFc^oF$F$?&F1FgemFb]n@$3-Fham6#/F^gq-F[o6$-Fg
o6$FOFdbuF`o/F`gq&FejnFizOF1F$F$F$6#FLFc\qt+F_dtF$F$F$O-Fa_n6$Fas-F\fp6$FggpFas
F$F$F$6#Fbr%+get_ObjectGt+F$6$%"OGFe`nF$F$C%>F1F:?(FinFLFL-F`rFferFb]n>F17$F]cn
-FA6%-F[o6$&FjbrFarF`oFcx&F_erFarOF1F$6$FjbrF_erF$6#FO%-get_SolutionGt+F$6*%"SG
%#SNGFhipFchm%&STempG%"gGFiip%*show_GoalGF$F$C(>F^ut+FeipF]jpF$F$C&>F1F\bt>FinF
:?(Fg\lFgjpF_]lFLFb]nC%>F<Fjjp@$-Fban6$F<FbuFibq@$F\[qC%>Fa[qFf[q@$Fi[q>FinF`\q
>F1Fb\qOFinF$F$6$Ff]vFa]l6#FL>F`xt+Feip6&%#t1G%#t2G%#t3GFe`nF$F$@%F\]q>Fbu7$-Fg
oFgil-FA6%Q:***~R&#7845;t~ti&#7871;c~F$F_sQI~~kh|_zng~gi&#7843;i~&#273;&#432;&#
7907;c.F$C)>Fdu-FguFgim>F^hl7$-Fgo6#F^hl-FgoF]x>F`hlFe]q>Fbu7$Fg_vQJ***K&#7870;
T~QU&#7842;~C&#7846;N~T|gwM~L|[w:~F$@%-F]bn6$F`hlFi]q?&Fg\lF`hlFb]n>Fbu7$Fg_v-F
A6&Q+~~~~~~~~~~F$F_sQ"=F$-F[o6$Fg\lF`o>Fbu7$Fg_v-FA6&F`avF_sFaav-F[o6$F`hlF`o>F
bu7$Fg_vQ_o|+*****~C|\wC~B&#431;&#7898;C~TH&#7920;C~HI&#7878;N~NH&#431;~SAU:~**
***F$?(Fg\lFLFL-F`rF]xFb]nC&>Fbu7$Fg_v-FA6%Q5~|+~*B&#432;&#7899;c~F$Fg\lQ$:*~F$
>F1-FA6$Q1~~~~~~Suy~ra:~~~F$-F[o6$&&FduFc]lF_\nF`o>Fin-FA6$Q7~~~~~~T&#7915;~:~~
~~~~F$-F[o6$&F]cvFd[nF`o@%0&F]cvFizF:C$>F<-FA6$Q2~~~~~~~~~~V|gy~:~~~F$-F[o6$Fgc
vF`o>Fbu7&Fg_vFinF1F<>Fbu7%Fg_vFinF1F$F$6,Fd]vF1Fe]vFinFiipF^uFf]vFa]lFhipF<6#F
L>F1F:>Fa]lF:?(Fe]lFLFL-F`rFhasFb]nC$>F17$F]cn-FA6'Q.|+|+~***~C|]wU~~~F$-F[o6$F
e]lF`oQ$~:~F$Q'~~T|gwM~F$-F[o6$&FcasF`]mF`o-F`x6#FeevOF1F$6%Fd_nF__nFcasF$6#FOF
__tt+6$%&tendsG%'kieudsG6&F[isFe`n%#thG%$thiGF$F$C%>F1F:?&FinFasFb]n>F17$F]cnFg
cr@%/F1FggpOFasC$>F<-&Faco6#%(permuteG6$FasFaeq?&Fg\lF<Fb]nC$>F1F:@$0Fg\lFasC$?
&FinFg\lFb]n>F1Fffv@$FhfvOFg\lF$F$F$6#FbrFcdnt+6$'%)Obj_nameGF`oF56$Fe`nF]inF$F
$C(>FinFO?(F1FLFL-F`rFhoFb]n@$-Fham6#/&&F9F_oFfrFasC$>FinFLFibq@$/FinFOOFjv@$3/
Fe`rFbr/FggpQ&resetF$C$>&FjhvFizF:Fgv@$/FgivF:>Fgiv-%,ReadCObjectG6#-FA6&FCQ'/d
ata/F$FasQ%.txtF$-Fhv6#FgivF$FhoF$6#Fbr%'ptdtvgGt+6$%"MG%"nGF$F$F$O/,&*&&FggpFf
rFL,&FhenFLF`ctF_]lFLFL*&&FggpFizFL,&F^fnFLF^gqF_]lFLFLFOF$F$F$6#FbrFgaqt+Fi`m6
%FhtFhflFe`nF$F$C&>FinF_s>F1Fadl@$3-F]bn6$FasF_bnFNC%@$-Fjgs6$FjaqFjbrOFb]n?&F<
F[bqFb]n@$5-FgaqFJ3-FhdrFJ-Fjgs6$7#F`^lFjbrOFb]nOF%OF%F$F$F$6#FL%0Find_Fact_Typ
esGt+6$Fj^rFh`q6$Fcin%&TypesGF$F$C%>FinF:?&F1FasFb]n@%Fbiv>Fin7$F\^l-F^hpF`jq>F
in7$F\^l-F^hpF_oOFinF$F$F$6#Fbr%)Unify_InGt+Fj\tFc^oF$F$C$?(F1FLFLF^]tFb]n@$-Ff
is6$FasFb]tOF1OF_]lF$F$F$6#Fbr%/Deduce_From53sGt+F$6(%&fact5GF\isF\]n%&vars5GFf
`nFhtF$F$?&F1Fc\nFb]nC(@$-Fban6$F1Fi_oF`dm>F</,&F[bpFLFj[rF_]lFO>Fg\l-FhanF_o?&
FinFc[nFb]n?&Fa]lFg\lFb]n@$-Ffis6$-Fe`pFarFa]l>F<-Fijm6$/Fa]l-FjwFarF<@$/-F`rFe
drFL>F<&&-Fb[o6%F<F_`oFLFfrFfr@$2Ff`wFb]lC%>Fi_o-Fa_n6$Fi_oFjbn>Fe]lF`gn@$FbgnC
&>F[hnF\hn>F__nF`hn>Fd_n7$Ff_n7&Q/Deduce_From53sF$F:<$F1FinFbhn>F]inFb]nF$6'Fcj
mF__nFd_nF]inFi_oF$6#FO%)AttrNameGt+Fi`m6&%#OSGF[isF[]n%"pGF$F$C(@$433F[\w/-Fgo
6$FOFasFcbn-F]bn6$-Fgo6$FbrFasFgdnOFas>F1-Fcdn6#-F[o6$-Fgo6$FOF^cwF`o@$-Fban6%-
F[o6$F^cwF`o&&-Ffim6#-Fgo6$FLFasFd[nFiz.FhtO&&F^dwFfr6#Fht>F<-Fijm6$-F_^o6$/&Fa
buFc^o&7#-Fgo6#F^cwFc^o/Fe`n;FL-F`r6#F`ewF_[o?&Fg\lF<Fb]n@$-F]bn6$Fg\lFc[rC%>Fi
nFco@&/Fd[tF^cw>Fin-FjwFc]l/F`fwF^cw>FinFd[t@$3Fbo-Fban6%Fg`tF]dwFcdwOFedwOFasF
$F$F$6#FL%)get_GoalGt+F$F$F$F$OFcasF$FhasF$6#FO%%tlptGt+6$FhjvFbhmF$F$F$O-Fijm6
$<$/FhenF`ct/F^fnF^gqFggpF$F$F$6#FbrF_jqt+6$Fb_rF5Fe_rF$F$C%>F1-Fhr6$f*F[sF$F\s
F$F\`rF$F$F$Fas?(FinFLFLF^`rFb]n@%Fd`rC$@$F``rOFb]n@$33/&Fa`rFfrF_hq-Fban6$Q)do
i~xungF$Fh`r-Fham6#/-F[o6$F1Fi]q-F[o6$Fa`rFi]qOFb]nC$@$F``rOFa`r@$FehwOFa`rOF%F
$F$F$6#Fbr%*Is_ObjectGt+Fi`mFc^oF$F$C$?&F1F9Fb]n@$-Fham6#/F_sF_hqOFb]nOF%F$F$F$
6#FL%'ptdtssGt+6$FhjvFj^uF$F$F$O/,&*&Fa[wFLF_[wFLFL*&F^[wFLFb[wFLF_]lFOF$F$F$6#
FbrF]jmt+Fi`m6)Fe`nFeal%&flag1GFi`nFdboFfhm%%usedGF$F$C*>Fe]lF`u>Fa]lF`u>Fg\l-F
hanFgim>F^uF`u?&F1Fg\lFb]n@$5Fjct3Fdcn-F]bn6$FfenFgdnC$>Fa]l<$Ff\mF1>Fg\l-Fhbn6
$Fg\lFjbn>Fa]l7$F]^lFf\m?&F1Fa]lFb]nC%>F<F%?&FinF^uFb]n@$-FfisFdjqC$>Fe]l<$F_]m
/F1Fin>F<Fb]n@$4F<>F^u<$-FgoF^]oF1OFe]lF$F$F$6#FL%/Deduce_From43sGt+F$6&%&fact4
GF\isF\]nFhtF$F$C$?&F1F^\nFb]nC$@$-Fban6$F1Fj_oF`dm?&FinFc[nFb]nC%>F<F`u@&-Ffis
6$F^`wF[bp>F<<#-Fijm6$/F^`wFj[rFin-Ffis6$F^`wFj[r>F<<#-Fijm6$/F^`w-Fe`p6#FcinFi
n@$F\_nC%>Fj_o-Fa_n6$Fj_oFjbn>Fg\l-Ff]n6#F[\q@$3F`dp4-F_^n6$F[\qF__nC&>Fedp7$Fg
dpF`^l>F__nF`_n>Fd_n7$Ff_n7&Q.Deduce_From4sF$F:F[bwF<>F]inFb]nOFehsF$6'FcjmFj_o
F]inF__nFd_nF$6#FOF_^nt+Fj\t6$Fe`nFfboF$F$@%-F]bn6$FasFi]qC$?&FinFasFb]n@$4-F_^
n6$FinFggpF^`qF\`qC$?(F1FLFLF^]tFb]n@$Fe^wF\`qF^`qF$F$F$6#Fbr%.Deduce_From8sGt+
F$FbitF$F$C$?&F1FcepFb]n@$4-Fban6$F1F\]uC$-F`itF_o>F\]u-Fa_n6$F\]uFjbnOFehsF$6$
FcjmF\]uF$6#FO%-Deduce_RulesGt+F$63Fe`nFeal%#CbG%%CombG%'ReRuleGF\]nFj`mFhtF^^p
F_^p%)CombTempG%#ctGF[is%*loaiToHopG%/TimDoiTuongNenGFbetFhflF$F$C(>Fg`mt+F$Fc^
pF$F$C)>FinFi^p>F<F^_p?(Fg\lFLFLFhdoFb]n@$Fc_p>Fe_pF[`p>F1F^`p>FduFe]n@$F]apC&>
FeapFfap>FbjmFjap>F]bpF^bp>F__nFabpOFcbpF$Febp6&FdcxFa]lFhtF`x6#FO>Fghlt+6%%)te
ndtmoiG%(tendtcuG%'varscuG6#FfboF$F$@%0FasFggp?&F1FefuFb]n@$/F_hqFasO<#-Fgo6#-F
^o6#FejnO9&F$F$F$6#Fe[n>Ffhlt+6$%&doisoG%&tohopG6)Fijv%)tohoptamGFi`n%&dothiGF`
fv%#coGFh`qF$F$C$>F1F_]l@%0F1F_]lC'>FinF:>F<F`u>Fe]l.%'chuacoG?&Fa]lFggpFb]nC%>
F<-Fbu6%&Fa]lF_oFe]lF<>Fe]lFjgx@$/F<<%F\\oFhco&Fa]lFd[n>Fin7$F\^lFa]lOFinOFggpF
$F$6$FhcxFghl6#Fbr>Fhhl-F^etFber?&F1FhhlFb]nC%>Fg\l-%+MyCombinatG6$F`jn7$FeerFd
gr>Fg\l-Ffhl6$F`jnFg\l?&F<Fg\lFb]nC&@$-Fban6$7$F<F1F`]uF`dm>Fa]l-%)ReplaceRG6$F
<F1>Fe]l-Fccp6$Fa]lF__n@$0Fe]lF`uC)>F`]u-Fa_n6$F`]u<#Fgix?&F^uFe]lFb]nC%@$-F]bn
6$F^uF\hq?&FinF^uFb]n@&3Ffdr4-F_^n6$FinFjbrC%@$FfcrF`dm>F_erF`er>FjbrFder3FjerF
afrC%@$FfcrF`dm>F]crFcgr>FggrFhgr>F`x-Ff]nF^]o@$331FLF`x1F`xF\^n4-F_^nFcbqC$>&F
cjmFi^o7$-Fgo6#Fe\yF^u>F__n-Fa_n6$F__n<#F^u>Fa_mF`u@$0&Fa]lFd\nFco>Fa_mF\ip?&84
F`epFb]n@$-F_^n6$-Fe`p6#Fc]y&&Fa]lF_\nFfr>Fi]y-F\fp6$-Fa_n6$Fi]y<#Fc]y<#Fg]y>Fd
_n7$Ff_n7&Q-Deduce_RulesF$F1Fi]y-Fa_n6$Fe]lFa_m>F]inFb]nOFehsF$6+F__nFcjmF]inFd
_nF`]uF_erFjbrF]crFggrF$6#FOFhant+6#Fap6$%"FGFe`nF$F$@)5-F]bn6$Fas%)constantG-F
]bnF`sF\ar55-F]bn6$FasFhjlFfbtF[\wOF\bt5Fcax-F]bn6$FasF\hqC%>F1F`u?&FinFasFb]n@
$4-Fban6$Fin<$FhenF^fn>F1-Fa_n6$F1FganOF1C$>F1-Fhan6#<#F[bqOF1F$F$F$6#FLFfjmt+F
i`m6$Fi`nFfhmF$F$C%>F1Fg[x>Fin-Fhr6$f*F[sF$F\sF$/Fas-F_bwFgimF$F$F$F1O-Fijm6$Fi
nFasF$F$F$6#FL%)Is_EqualGt+6$Fcio%&expr2G6%F]inFe`nFealF$F$C'@$3F\`y-F]bn6$Fggp
F\hqC%@$0FaeqF^]tF^`q?(FinFLFLFaeqFb]n@$4-F_by6$&FasFar&FggpFarF^`qF\`q@$3Fcax-
F]bn6$FggpFi]qC%?&FinFasFb]nC%>F1F%?&F<FggpFb]n@$-F_by6$FinF<C$>F1Fb]nFibq@$4F1
F^`q?&FinFggpFb]nC%>F1F%?&F<FasFb]n@$F]dyC$>F1Fb]nFibq@$FbdyF^`qF\`q>F1-Fham6#/
FasFggp@$33/F1F%4Fe_yFcey@&3-F]bn6$Fas%(polynomG-F]bn6$FggpFhey>F1-Fham6#/-%)si
mplifyG6#-%'expandG6#,&FasFLFggpF_]lFO3-F]bn6$FasFc[r-F]bn6$FggpFc[r>F1-Fham6#/
-F`fy6#-Fcfy6#,&-%$absG6#,&Fa_tFLFa^tF_]lFL-Fegy6#,&-Fe`pF_]tFL-FjwF_]tF_]lF_]l
FO-FhvF_oF$F$F$6#FbrFccpt+6$F]^pF__n6$Fcin%(setfactGF$F$@%-F_^n6$FfgqFggpC%>Fin
F`u?&F1&FggqFizFb]n@$4Fhdt>FinF[et-FhvFarF\arF$F$F$6#FbrF_iqt+F[sFgdwF$F$C%@$Fe
_yC$>F1-FR6$Q"[F$Fas@%Fj[m-Fhv6#-F]y6$FasFb\m-FhvFgim@$Ffbt-Fhv6#-F[o6$FjbwF`o-
Fhv6#Q"?F$F$F$F$6#FL%'ptdt2dGt+6$%"AG%"BGF$F$F$O/,&*&F_[wFL,&Fa[wFLF^gqF_]lFLFL
*&,&F^[wFLF`ctF_]lFLFb[wFLF_]lFOF$F$F$6#Fbr%(ptdssdtGt+F`gwF$F$F$O/,&*&-%&coeff
G6$F[hyFhenFLF_[wFLFL*&-Fj[z6$F[hyF^fnFLFb[wFLFLFOF$F$F$6#FbrF[`qt+Fi`mF$F$F$C$
@(5-Fban6$FasFjbr-Fban6$FasF]crF\`q3Fhbw5-Fban6$FadwFjbr3-FhdrF`dw-Fjgs6$7#-Fgo
F`dwFjbrF\`q3-FhdrFgimF_\wF\`qF^`qF$F$F$6#FLFjixt+6$'%%combGF\hqF]^p6$Feal%'rer
uleGF$F$C%>Fin-Fijm6$-F_^o6$/&Fa[wFc^o&FasFc^oF_eqFggp?&F1&&FinF_\nFfrFb]n@$/Fe
]nFL>Fin-Fijm6$/Fejn-F[o6$-Fijm6$F_^zF]fxF`oFinOFinF$F$F$6#FbrFjgst+6$%&list1G%
&list2G6&Fe`nFealFjjyFa[xF$F$C'>F<Fggp@$2F^]tFaeqOF%@$4-%'subsetG6$-F[oFdax-F[o
FfcyOF%?(F1FLFLFaeqFb]nC%>Fg\lFO?(FinFLFLFhdoFb]n@$/&F<Far&FasF_oC%>F[azFco>Fg
\lFLFibq@$/Fg\lFOOF%OFb]nF$F$F$6#Fbr%+Has_ObjectGt+Fi`mFc^oF$F$C$?&F1FasFb]n@$4
-F[jwF_oOF%F\`qF$F$F$6#FLF^hpt+6$%(elementGFh`q6'FhtFe`n%&OtypeG%&nameAGFbbwF$F
$C$@*-Fban6%FasFjbr.F1-Fhv6#&F_erF_oFhbwC&>F<-F^hpF`dw@$/F<Fhcr-Fhv6#Fhcr>Fg\lF
^cw@%-F]bn6$Fg\lFgdn-Fhv6#-F_iqFc]lC$>Fa]lF_dw@$-Fban6%Fas&F_hxFfrFhbz-Fhv6#&&F
_hxFizF_oFfbt-FhvFfctFfaq?&FinF[blFb]n@$3/F]guF`jy5-Fham6#/&FinFd[n7#-F_^o6$-F^
hp6$FfbuFLFgbu3-Fban6$F[iwFf^z/-F[o6$F]ezFi]q<#F_ez@%Fbiv-Fhv6#FerF]iyFaczF$F$F
$6#FbrFgcqt+6&Fe`qFgal%'giatriGFfal6)%)funcnameGF[is%#gtGFfhmFe`n%'ketquaG%+tin
hgiatriGF$F$C+>F^ut+6$FcfzFijv6$%'resultG%$gttGF$F$C%>F1F`u@%-Fban6$Q#xdF$FasC$
>F1<#-Fijm6$FbuF^iu@$0&T(Fd[nF:@%/FggpF`\nC$@$-Fham6#/&&FduFd[nFizF_`t>Fdhz-Fij
m6$/&FdhzFfr-F^o6#-FA6$FihzFi`tFdhz>F1-Fa_n6$F1<$Fihz-Fgo6#&FduFd\nC%>F_aq7$-Fg
o6#F_aqFihz>Faaq7$-Fgo6#FaaqFchz>Fcaq7%-Fgo6#FcaqFihzFbizC$>Fin-F^hl6#F[bq@$0Fi
nFjvC%>F1<#/FfgzFin@$Figz@%F]hzC$@$5F`hz-Fham6#/FchzF_hp>FdhzFfhz>F1-Fa_n6$F1<$
Fbiz/FihzFinC%>F_aqFgiz>FaaqF[jz>Fcaq7%F`jzFi[[lFbiz>F1-Fa_n6$F1FegzOF1F$F$6*Ff
hmFg\lF[isFinFe`qFasFbfzF16#Fbr>Fg\lF`u?(Fa]lFLFLF^]tFb]n>Fg\l-Fa_n6$Fg\l<#/&&F
^gqFfrFg\m&FggpFg\m@$0F`gqF:@%/Fe`rF`\n>Fg\l-Fa_n6$Fg\l<#/&F`gqFfr9'C$>Fg\l-Fa_
n6$Fg\l<#/Fh][l-FA6$Fh][lFe]u>Fe]u,&Fe]uFLFLFL>Fin-Fijm6$Fg\lFas>F1-F^o6#Fggq>F
e]lF`u@%-F]bn6$F`fxFi]q?&F<F`fxFb]n>Fe]l-Fa_n6$Fe]l<#-F^u6$F<Fe`r>Fe]l-F^u6$F`f
xFe`rOFe]lF$6&F_aqFaaqFcaqFe]uF$6#F`\n%,Is_DacTrungGt+6$%#O1G%#O2G6$F]^pFaetF$F
$C$?&F1&-Fcdn6#-F^hpF_]tFjbpFb]n@$-Fham6#/F_hqQ3xac_dinh_doi_tuongF$C$>Fin-Fhr6
$f*F[sF$F\sF$-Fcbn6$FdjpFasF$F$6$F_`[lFggpFhep@$-Fham6#/FasFinC$@$5/Ff`[lF_`t/F
f`[lF_hp@$-Fham6#/&F[bqFizFj^uOF%OFb]nOF%F$F$F$6#FbrFfist+6$FfboFgbo6/%#k1G%#k2
GFdboFeboFe`nFealFcbwF[isF[]n%%tam1G%%tam2G%'TestDXG%(Func_DXGF$F$C)>Fdhlt+F$6,
%&type1G%&type2GFet%#n2GFe`nFealFhtFcioFbbyF]inF$F$C*@$0&FdjpFfr&F_`nFfrF^`q>F1
Fdjp>F<-F`rF`du>FinF_`n>Fg\l-F`r6#F_`n?(Fa]lFbrFLF<Fb]n@%-F]bn6$&F1Fg\mFgdn>Ffd
[l-F[o6$-Fgo6$FOFfd[lF`o>Ffd[l-F^hp6$Ffd[lFL?(Fa]lFbrFLFg\lFb]n@%-F]bn6$&FinFg
\mFgdn>Fce[l-F[o6$-Fgo6$FOFce[lF`o>Fce[l-F^hp6$Fce[lFL@'5-F__r6$F1F[iw-F__r6$Fi
nF[iwC'>F`x-F[o6$&Fdjp6#;FbrF<Fi]q>Fa_m-F[o6$&F_`n6#;FbrFg\lFi]q?&Fa]lF`xFb]nC%
>Fg`mF%?&Fe]lFa_mFb]n@$-Ffis6$Fa]lFe]l>Fg`mFb]n@$/Fg`mF%F^`q?&Fa]lFa_mFb]nC%>Fg
`mF%?&Fe]lF`xFb]n@$Fdg[l>Fg`mFb]n@$Fhg[lF^`qF\`q0F<Fg\lF^`qC$?(Fa]lFbrFLF<Fb]n@
$4-Ffis6$&FdjpFg\m&F_`nFg\mF^`qF\`qF$F$6&FfboFasFgboFggp6#FO>Fehlt+F$6(FhjlFcc[
lFdc[l%)tinhchatGFe`qFf`nF$F$C%@$/F_`nFdjpOFb]n@$33/-Fgo6$FOF_`n-Fgo6$FOFdjp/-F
`r6#7#-FgoFad[lFcdu/<#F_j[l<#F_duC'>F1-F[o6$Fgi[lF`o>Fin-F_]wF]j[l>F<-F_]wFddu@
$3-FjgsF^dy-FjgsFfdo?&Fa]lF[blFb]n@$33-Fham6#/F1Fhco-Fjgs6$FinF_hx-Fjgs6$F_hxFi
nFibq@$-Fban6$F[iwFj]yOFb]nOF%F$F$6&FgboFggpFfboFas6#FO>F1-Ff]nFgim>Fin-Ff]nF_]
t@$0F1FinOF%@8/F1FL@$-Ffis6$F`ctF^[w@%5/-F^hp6#F`ctFfht/F`]\lQ%EDGEF$C%>Fg`m<#-
Fgo6#-F^oFdgq>Fbbm<#-Fgo6#-F^o6#Fa[w@$/Fg`mFbbmOFb]n@$-Fham6#/F^gqFa[wOFb]n/F1F
br@(-F_byF]_rOFb]n333Ffbt-F]bn6$FggpFgdn-F_by6$Fjbw-Fgo6$FOFggp/F^ay<#-FgoF_]tC
%>Fa_m&-FcdnF_jyFa]n>Fa_m-Fijm6$-F_^o6$/&7#-Fgo6#-F^o6#&F[`\lFfrFg\m&FjaqFg\m/F
a]lFhbuFa_m?&F^uFa_mFb]n@$53-F]bn6$F^uFc[r3/7#-Fgo6#-Fe`pF^]oFjaq/7#-Fgo6#-FjwF
^]o7#Fg_\l3/Fha\lFjaq/Fca\lF\b\lOFb]n3333Fhbw-F]bn6$FggpF_bn/Fc_\lFcbn-Ffis6$Fa
dw-Fgo6$FLFggp5/Fjay-F_bwF_]t3-Ffis6$-Fgo6$FLFjay-Fgo6$FLF^c\l/-Fgo6$FbrFjay-Fg
o6$FbrF^c\lOFb]n/F1Fe[n@*3-F_by6$Fa_tF[hy-F_by6$Fa^tF\hyOFb]n3-F_by6$Fa_tF\hy-F
_by6$Fa^tF[hyOFb]n3-FfisF`d\lFad\lOFb]n3-FfisFfd\lFed\lOFb]n/F1F`\n@&3F[e\l-Ffi
sFbd\lOFb]n3F^e\l-FfisFhd\lOFb]n/F1Fe\n@'-F_by6$,*Fa_tFLFa^tF_]lF[hyFLF\hyF_]lF
OOFb]n-F_by6$,*Fa_tFLFa^tF_]lF[hyF_]lF\hyFLFOOFb]nC'>F<Fg[x>Fg\l-FhanF_]t>F`xFg
gp?&Fa]lF<Fb]n?&Fe]lFg\lFb]n@$Fdg[l>F`x-Fijm6$/Fe]lFa]lF`x@$30F`xFggp-Ffis6$Fas
F`xOFb]n/F1Ff^m@%F^eyOFb]nO-FdhlF$/F1FginO-FehlF$/F1F[cp@$/,&Fa^tFLF\hyF_]lFOOF
[e\l/F1Fbgs@%-Fham6#0Fa_tF[hyOF%OFce\l/F1"#5C$@$3Fce\lF[e\lOFb]n@$Fee\lOFb]n/F1
F\^n@$F\eyOFb]nOF%F$F$F$6#Fbr%+xuly_HyposGt+6#%'SHyposG6&Fe`nFiar%*read_factG%*
read_funcGF$F$C&>Fint+F]brF_brF$F$C$>F1Fbbr?&FinF1Fb]n@)FccrC&@$FfcrF`dm>F`crFj
cr>F^drF_dr?&F<FcdrFb]nFddrFfdrC%@$FfcrF`dm>F_erF`er>FjbrFderFgerC'@$FfcrF`dm>F
_erF^gr>FjbrFagr>F]crFcgr>FggrFhgrC%@$FfcrF`dm>F]crFcgr>FggrFhgrF$F$6$FiarFin6#
FL>F<t+Fc^oF`[sF$F$C&>F<F`u>Fin7#Fedu?&Fg\lFinFb]nC$>F1F`\s@$Fb\sC%>Fj^rF[]s>F_
]sF`]s>F<Fd]s-FbuFJF$F$Ff[]l6#FL>Fg\lt+Fc^oF`[sF$F$C&>F<F`u>FinF]\]l?&Fg\lFinFb
]nC$>F1F`\s@$F[_sC%>F__sFb_s>F_]sF`]s>F<Fd]sFf\]lF$F$Ff[]l6#FL?&F1FasFb]n@%4-Fg
aqF_o-F<F_o-Fg\lF_oF$6,Fj^rF__sF`crF^drF\fsFcjmF]crFggrFjbrF_erF$6#FLF\ftt+F$6+
FafqFfhmFf`nFcinFi]t%#vtG%#vpGFcfqFdfqF$F$C'>F1F:>F`xF:?&Fg\lF`gsFb]nC(>Fe]l-F^
hp6#Fd[t>Fa]l-F^hp6#F`fw>F^u7%F\\oFhcoF_hx>Fe]l/Fe]lF^u>Fa_m-Fcjq6$Fe]lF1@%/Fa_
mF_]lC$>F17$F]cnFe]l>F`x7$-FgoFi^oFL>&F`x6#Fa_m,&F]`]lFLFLFL?&Fg\l&FcjmFa]nFb]n
C&?(F<FLFLFb]lFb]n@$4-F]bn6$&Fg\lFJF`o>Fh`]l-Fijm6$/Fh`]l-F^hp6$Fh`]lFLFh`]l>Fg
\l-F_jq6$Fg\lFL>Fa_m-FcjqFchq@%Fe_]lC$>F17$F]cnFg\l>F`xFj_]l>F]`]lF_`]lOFd]pF$6
%FcjmFjbrF_erF$6#FOFceqt+Feip6'Fifl%$demG%$lanGFbet%+time_DeterGF$F$C%>F1t+F$F$
F$F$C'>%&FoundGF%>F]inFb]n>FbuFO>FduFO>FguF_\uF$F$6(F_b]lFinF`b]lF<Fab]lFa]l6#F
OFigm?(F$FLFLF$34Fgb]lF]inC;@$2"$+#,&F_\uFLFa]lF_]lC$-Fi_u6#Q.~Out~of~time.F$Fi
bq>F]inF%>F<,&F<FLFLFL-F`]q6%Q2~**L&#7847;n~=~%aF$F</%&colorG%$redG@$0F`[nF]bpC
%-Fh[p6#Q.vao~deduce~3sF$F`gp@$F]inC$>Fgb]lF]]qF`dm@$0<#F\\nFj_oC%-Fh[p6#Q/vao~
deduce~43sF$-Fi]xF$@$F]inC$>Fgb]lF]]qF`dm@$0<#Fa\nFi_oC%-Fh[p6#Q/vao~deduce~53s
F$-Fj^wF$@$F]inC$>Fgb]lF]]qF`dm@$0<#FaepF\]uC%-Fh[p6#Q.vao~deduce~8sF$-F_bxF$@$
F]inC$>Fgb]lF]]qF`dm@$0<#-Fgo6#F`gsFhgsC%-Fh[p6#Q0vao~deduce~983sF$-FhhsF$@$F]i
nC$>Fgb]lF]]qF`dm-Fh[p6#Q0vao~deduce~ObjsF$-%/Deduce_ObjectsGFgim@$F]inC$>Fgb]l
F]]qF`dm@$F^g]lC%-Fh[p6#Q.vao~deduce~9sF$-FjfsF$@$F]inC$>Fgb]lF]]qF`dm-Fh[p6#Q)
vao~luatF$-F_cxF$@$F]inC$>Fgb]lF]]qF`dm-Fh[p6#Q3vao~Deduce_EqsGoalF$-%/Deduce_E
qsGoalGFgim@$F]inC$>Fgb]lF]]qF`dm-Fh[p6#Q(vao~hamF$-%-Deduce_FuncsGFgim-Fh[p6#F
]in@$F]inC$>Fgb]lF]]qF`dmFibq@$0F_aqF:@$2FinFbrC(-Fh[p6#QN--------------THEM~DO
I~TUONG~MOI~VAO---------F$>Fin,&FinFLFLFL>Fjbr7$FeerFhiz>F_er7$FaerF\jz-FadqFaj
z>F]inFb]nF$6&Fgb]lF]inFjbrF_erF$6#FLF^ent+6#%&biensG6(%*get_valueG%*giatridonG
%-cacgiatridonG%+tachgiatriGFgal%'valuesGF$F$C(>F1t+6#Fgal6%FcinFhipFealF$F$C(>
FinF`u@$-F_^n6$FasFf_p>Fin-Fa_n6$Fin<#Fbgz?&F17$Fa[nFaepFb]n@$-Ffis6$FjayF[bp>F
in-Fa_n6$Fin<#Fj[r@$3-Fban6$F]hpF_er/FinF\]^l?(F<FLFL-F`rFajmFb]n@$334-Fham6#/F
as&FbjmFJ-F[`[l6$<#Fd^^lFas/-F^hp6#Fd^^lQ(PTDT_TQF$>Fin-Fa_n6$Fin<#-FbuFj^^l@$3
1FbrF_r-Fban6$FbgzFin>Fin-FhbnF[]^l@'/F_rFOOQ$cxdF$FfjnOF\^lOFinF$F$6$Fj[^lF16#
FL>Fint+6#F`fzFc^oF$F$C$?(F1FLFLFaeqFb]n@$-F]bn6$F\azFi]qOF1OFOF$F$F$6#FL>F<t+F
b`^l6#FcfzF$F$C$?&F1FasFb]n@$0-FbuF_oFOOF%OFb]nF$F$6$F[\^lFin6#FL>Fg\lt+Fb`^l6(
FhtFe`nF[is%%seq1G%%seq2G%+giatritempGF$F$C%>Fe]lFas?(F$FLFLF$4-FbuF`]m?(FinFLF
L-F`rF`]mFb]nC$>F1-Fdu6#&Fe]lFar@$FNC'>Fg\l-F_^o6$&Fhb^lFfgu/FealFb\m>Fa]l-F_^o
6$F^c^l/Feal;Feil-F`rFgb^l>F<-Fhr6$f*F[sF$F\sF$7%FbuFasFduF$F$6&Fja^lFg\lF[b^lF
a]l&Fhb^lF_o>Fe]l-Fijm6$/Fhb^lF`^lFe]lFibqOFe]lF$F$6&F\\^lF<F[\^lFin6#FL@%F\`yC
%>Fe]lF:?&Fa]lFasFb]n>Fe]l7$F_]m-F1Fg\m@$0-FinF`]mFO>Fe]l<#-Fgo6#-Fg\l6#7#Fe]l>
Fe]l-F1FgimOFe]lF$6$FcjmF_erF$6#FL%*SolveFactGt+6$Fcin'Fi`nFi]q6$FapFe_zF$F$C%@
%/Fe`rFe[nC$>F1-F`fy6#-%,dongian_ptOGFgim>Fin-Fb[oFidt>Fin7#-Fb[o6$Fas-%(SetVar
sG6$Fa_t%&nameOG@$/FinF`uFgvF[fzF$F$F$6#FbrFfi]lt+Feip67%%goalG%)typegoalGFht%&
ValueG%"vG%)VarsTempG%%VarsG%$ansGFd`q%)RuleFuncGFjfx%*find_ruleG%,test_valuesG
%+find_fact8G%*rule_funcG%,find_fact10G%+find_fact9G%2find_fact3_objectG%*Has_E
qualG%,DongNhat_PtG%,find_fact11GF$F$C@>86t+6$%#eqG%$EqsG6&%#eeG%"eG%$ecoG%(Eqs
TempGF$F$C%>Fg\lFggp?&F1FasFb]nC%>F<F%?&FinFggpFb]n@$-F_by6$FinF1C$>F<Fb]nFibq@
$Fc]x>Fg\l-Fa_nFd\xOFg\lF$F$F$6#Fbr>Fehlt+6$%'tohopsG%(giatrisG6$Feal%,giatrist
empGF$F$C'>FinFggp@$Fecy>FinF^[w@$FfjnOFb]n@&Faf^l@$3-Fban6$F[`^lFin0F[er<#F[`^
lOFb]nFe[_lOFb]nOF%F$F$F$6#Fbr>Fdhlt+F$6)F]^p%&combsG%#cbGFj]zFi]t%"cG%)giathie
tGF$F$C&>Fa]lF:?&F1F\_lFb]nC$>Fin-F\ix6%F`jnFjbrFL?&F<FinFb]n@$-Fbu6$F<-F^enFJC
%>Fg\lFiix@$/<#-Fgo6#&Fg\lFd[n<#F_hpC$>F^u&&&Fg\lF_\nFfrFfr@$3-Fban6$Fhz7#-Fgo6
#&F^uFd[n55/<#-Fgo6#-F^en6#7$FhzFe^_lFh[_l/Fi^_l<$F[`^lFbgz/Fi^_lF\]^lF`dm@$-F_
^n6$F\^_lF__nC$@%4-Fban6$Fc]\lFg]_l>Fa]l7$Fg\lFf\m>Fa]l7$Ff\mFg\l?&Fe]lF<Fb]n@$
4-Fham6#/-F^hpF`]mFfht>Fdu-Fc\q6$FduFe]o>Fgu7$F]bmFf\m>F^hl7$Fa`v-F_^o6$Q%ruleF
$/Fe`n;FL-F`rFg\mF$F$6*F`h^lFehlF\h^lF^uF^h^lFg`mFjfxFbbm6#FO>Ffhlt+F$FbitF$F$?
&F1FcepFb]n@$-Fbu6$7#-Fgo6#F[bp-F^en6#Fja_lC%>Fdu7$Fc`vF1>Fgu7$F]bmQ&fact8F$>F^
hl-Fc\q6$F^hl<#F[b_lF$F$6*F`h^lFehlF^h^lFg`mFjfxFbbmF\h^lF^u6#FO>Fc]yt+F$F\gsF$
F$?&F1F`gsFb]n@$-Fbu6$7$F[bpF]hs-F^en6#Fac_lC%>FduFab_l>Fgu7$F]bmQ&fact9F$>F^hl
-Fc\q6$F^hl<$F[bpF]hsF$F$Fib_l6#FO>Fhhlt+F$6#%'fact10GF$F$?&F1&Fcjm6#Fih\lFb]n@
$30-F`r6#Fhb_lFL-Fbu6$7$F[b_lF]hs-F^en6#F\e_lC%>FduFab_l>Fgu7$F]bmQ'fact10F$>F^
hl-Fc\q6$F^hl<$F[b_lF]hsF$F$Fib_l6#FO>88t+F$6&%'fact11G%,vars_fact11GFjg^l%*var
s_funcGF$F$?&F1&Fcjm6#F\^nFb]nC&>FinFh_w>Fg\lF`u?&F<FinFb]n>Fg\l-Fa_n6$Fg\l<#F`
^l@$-Fbu6$7#F]^l-F^en6#F^g_lC%>FduFab_l>Fgu7$F]bmQ'fact11F$>F^hl-Fc\q6$F^hlFg\l
F$F$Fib_l6#FO>85t+F$6*F\is%*constructG%$objG%$attGFb\_lFi`nFeal%(varstemGF$F$?&
F1Fc[nFb]n@$-Fban6$F[bpF]crC$>Fin&-Ffim6#&F[b_lFfrFd\n@$0FinF:?&Fa]lFinFb]n@$-F
fis6$FgepF[bpC*>Fe]l-Fhan6#-FjwFg\m?&F^uFe]lFb]n@$3-F]bn6$F^uF_bn0-Fgo6$FOF^uFc
bn>Fe]l-Fa_n6$-Fhbn6$Fe]lF\]y-Fhan6#Ff]x>F`xF`u?&F^uFe]lFb]n@%3Fji_l/F]j_lFcbn>
F`x-Fa_n6$F`x<#&Ff]xFfr>F`x-Fa_n6$F`xF\]y>Fd_n7$Ff_n7&Q2find_fact3_objectF$F`u<
$F1Fa]l<#/Ffi_lFj[r>Fbu7$Fg_v7%Fi[`l7$F[`]lF[bpFe]l>Fdu7$Fc`vQ-fact3_objectF$>F
gu-Fc\q6$Fgu<$F[bpF[`]lF$F$6(F^h^lFg`mFjfxFbbmF\h^lF^u6#FO>87t+6$%$pt1G%$pt2G6(
%%sh11G%%sh21G%%sh31G%%sh12G%%sh22G%%sh32GF$F$C)>F1-Fj[z6$Fa_tFhen>Fin-Fj[z6$Fa
_tF^fn>F<,(Fa_tFL*&F1FLFhenFLF_]l*&FinFLF^fnFLF_]l>Fg\lFi[z>Fa]lF]\z>Fe]l,(F[hy
FL*&Fg\lFLFhenFLF_]l*&Fa]lFLF^fnFLF_]lO<%/F1Fg\l/FinFa]l/F<Fe]lF$F$F$6#Fbr>Fghl
t+6$F`fzFgg^l6;FbfzF\b^l%$eq2GF_i^l%#EqG%#rfGF`^]lFa^]lF^i^lFealFj`m%%exgtGFfhm
%$ngtG%)goaltempGFjg^lFh]t%+test_solveG%-GetVars_PolyG%+get_valuesG%*solve_eqsG
%,init_valuesGFj[^l%)find_eqsG%*test_varsGF$F$C0>8:t+6%Fgal%(tapbienG%&tapgtG6$
%"bGFcfzF$F$C%>FinFe]q@$5/FinF[`^l/FinFbgz?(F1FLFLF^]tFb]n@$-Ffis6$Fb]tFasO&F`f
xF_oOFinF$F$F$6#Fe[n>Fh\`lt+6%Fh[^lFa``lFb``l6$Fd``l%$gtsGF$F$C%>FinF:?&F1FasFb
]n>Fin7$F\^l-Fbu6%F1FggpF`fxOFinF$F$6$Fj[^lF^``l6#Fe[n>89t+6$Fh[^lFij^l6,Fd``lF
[[_l%+init_valueGF[isFbfzF`^]lFd^pFcfzFi]t%*bienstempGF$F$C(>F<t+Fb\^l6)%#b1G%#
b2G%%gtb1G%%gtb2G%&btempGFh`q%*ds_valuesGF$F$@(/F]hpFc]\lO7$F`ctF^gq5-Fham6#/F]
hpF_`t3-Fham6#Fdc`lFebtC$>Fbu-Fa_n6$Fbu<#/F`ctFLO/,(*&FhenFLF`ctFLFL*&F^fnFLF^g
qFLFLF`gqFLFO3F\d`lFfbtC,>F1F[bq>FinFejn>F1F_hq>F<-F^hl6%F1FduFgu>Fg\l-F^hl6%Fi
nFduFgu@$5/F<F[`^l/F<Fbgz>F<-F`hlF_o@$5/Fg\lF[`^l/Fg\lFbgz>Fg\l-F`hlFar>Fbu-Fa_
n6$Fbu<#/,&&Fg\lFizFL&F<FizF_]lFL@%43-F]bn6$F[\qFgdn-F]bn6$Fgf`lFgdn>Fa]lF<>Fa]
lFg\lO/,&*&,&Ff[pFLF[\qF_]lFL,&FhenFLF\\oF_]lFLFL*&Fef`lFL,&F^fnFLFhcoF_]lFLFLF
OF$F$6,Fi]tFa_mFhb`lFg`mF[[_lFinFj[^lFbuFgb`lF<6#FL>Fa_mF`u>FinFggp>Fg`mFas?(F1
FLFLFaeqFb]nC$>F`x-Fbu6%F\azFasFin@$5/F`xF[`^l/F`xFbgz@%-Fgaq6#F\azC'>Fg\l-Fgu6
$7#-FgoFih`l-Fdu6%F^i`lFasFin>Fa]l-Fdcq6#-F^hpFih`l>Fa]l-F^o6#Fj]y>Fe]l-Fa]l6#-
Fgo6#Ff[p>&FinF_oFe]l>F_j`l-F<Fih`lO7$FinFa_mF$F$6(Fj[^lF^``lFg_`lFh\`lFi_`lFcb
`l6#Fbr>F[i^lt+F]_yF^_yF$F$@)Fa_yOF`u5Fg_y3F[\w-Fham6#/FjbwQ".F$OF\btF[`yC%>F1F
`u?&FinFasFb]n>F1-Fa_n6$F1-FbuFarOF1C$>F1-FbuF]ayOF1F$F$6$Ff_`lF[i^l6#FL>F[h_lt
+6#%$ptsGF$F$F$C%>Fbu-FduFgim@$2Faeq-F`rFgilOF%OFb]nF$F$6&F]h^lFbhlFf_`lF[i^l6#
FL>8<t+6$Fbi^lFb\al6(F[c[lF\c[l%%var1G%%var2G%#jjGFi]tF$F$C+>F<-FbuFgim>Fg\l-Fb
uF_]t@$0-F\[pF[[sF`uOFb]n>F1F`u?&Fa]lF<Fb]nC$>Fe]l-F[o6$Fa]lF`o@%1Fe[n-FbyF`]m>
F1-Fa_n6$F1<#-F^o6#-F]y6$Fe]l;FL,&Ff^alFL!"$FL>F1-Fa_n6$F1F`fp>FinF`u?&Fa]lFg\l
Fb]nC$>Fe]lFb^al@%Fe^al>Fin-Fa_n6$FinFj^al>Fin-Fa_n6$FinF`fp@$0-F\[pFdjqF`uOFb]
nOF%F$F$F]\al6#Fbr>8;t+6#%$eqsG6(Fbi^l%&tapptGFhflFaetFai^l%+tappt_tempGF$F$C'>
FinF:>Fe]lF:?&F1FasFb]nC$@$3-Fbu6#Fjbn0FjbnFduC$>Fe]l7$F_]mFjbnF`dm@%F]i_lC%>Fg
\lF%?(F<FLFLF_rFb]n@$-Fgu6$F1&FinFJC$>Fbbal-Fa_n6$FbbalFjbn>Fg\lFb]n@$4Fg\l>Fin
7$F\^lFjbn>FinF[cal?(F1FLFLF_rFb]nC$@$FfjnO7$F_]mF\^l?(Fa]lFeilFLF_rFb]n@$1Fa]l
F_r@$0-F\[p6$Fce[lF_j`lF`uC&>F_j`l-Fa_n6$F_j`lFce[l>Fin7$-F_^o6$&FinFc^o/Fe`n;F
L,&Fa]lFLF_]lFL-F_^o6$Fadal/Fe`n;,&Fa]lFLFLFLF_r>Fa]lFddal@$FfjnOFacalOFacalF$F
$6(Fe_`lF[h_lF`_`lFa]lF[``lF^]al6#FL>Fje_lt+6#Fd_`l6.%'nghiemGFijvFi]tFhfl%#taG
%$thuG%'thutamG%$roiG%#niGFdi^l%$itaG%#kqGF$F$C'@$/FbuF`uOF$?&FbbmFbuFb]n@$/-Fe
`pF^go-FjwF^go>Fbu-Fhbn6$Fbu<#Fbbm>F<-FduFgil>FguFO?&Fa]lF<Fb]nC$@$/Fa]lF`uF`dm
@$-F^hlFg\mC+>F1-Fb[o6$Fa]lF`hl@$/F1F`uF`dm>FdhlF`u?&FinF1Fb]nC$?&Fa_mFinFb]n@$
45555-F]bn6$-FjwF^`]l%(integerG-F]bn6$Fdhal%)fractionG-F]bn6$Fdhal%&floatG-F]bn
6$Fdhal%"^G-F]bn6$Fdhal%"*G>Fin-Fhbn6$Fin<#Fa_m@$FfcpC$>F^u-Fijm6$FinFbhl?(Fg\l
FLFL-F`r6#FjdmFb]n@$/-Fhbn6$-F`em6#&F^uFc]lFe`yF`uC$@%5/-F^hp6#&FjdmFc]lF_`t/Fi
jalF_hp>Fe]l/-Fcbn6$F[[blFf`nFdjal>Fe]l/F[[blFdjal@$4-F_^n6$Fe]lFc[nC&>Fc[n7$Fa
[nFe]l>F__nFc]o>F]inFb]n>Fdhl-Fa_n6$FdhlFe]o>Fd_n7$Ff_n7&7#Q/Deduce_EqsGoalF$F:
Fa]lFdhl@$2FLFehqC$>FguFLOF$>FbhlF^u>Fbu-Fijm6$FinFbu?&FbbmFbuFb]n@$Fbfal>FbuFf
falF$F$62F_i^lFg\lFj_`lFg`alFc_`lFfhlFe_`lF[h_lF]h^lFbhlF\b^lFinF\h^lFbuFf_`lF[
i^l6#FL>Fin-Fcb`l6$FbuFas>Fa]lF]gu>FinFer>Fg\lF`u>FghlFggp?(Fe]lFLFLF^bvFb]nC(@
.-Fham6#/&FguF`]mF^a_lC&>F<F`u@%0&&&FduF`]mF_\nFizF`u>Fa_mFd^blC&>F1-Fgo6$FO&Ff
^blFd\n>Fc]y-Fh\`l6%&Ff^blFizFbuFin>Fa_m<#-F16#-FgoFh]y>Fc]y<#-F_^o6$/&F`_blF_f
o&Fc]yF_fo/Fg`m;FL-F`rFh]y@$5-Fban6$Fhen-F[i^lF^`]l-Fban6$F^fnFd`blC%>Fbbm-F[o6
$-Fgo6#-Fhbn6$Fd`blFe`yF`o>Fbbm-F^o6#-F]y6$Fbbm;FL,&-FbyF^goFLFa_alFL?(Fg`mFLFL
Fh\alFb]n@$/&FbuF_foFbbmC$>&FinF_fo-FgoF^`]l>F<<#/FbbmF^bbl@%/F<F`uC$>Fg\l-F^hl
6$Fa_mFg\l>Fd_n7$Ff_n7&Q?Thiet~lap~phuong~trinh~tu~luatF$Ff^bl-Fa_n6$&Fe^blFfrF
c]yFa_m>Fd_n7$Ff_n7&F[cblFf^blF\cblF<-Fham6#/F_^blFdb_lC+>F1-Fdcq6#-F^hp6#-Fe`p
6#Ff^bl>F1-F^o6#Fiep>Fc]y-Fh\`l6%7#-FgoFjcblFbuFin>F^uFc_bl>Fc]y<#-F_^o6$/&Fcdb
lF_foF\`blF]`bl>F`x-FjwF\dbl@'33Fijx-F]bn6$F`xF\hq/-F`rF^]oFh^oC$>Fa_mF`u?(Fg`m
FLFLFdeblFb]n>Fa_m-Fa_n6$Fa_m<#/&F^uF_fo&F`xF_foF_a\l>Fa_m-F`hl6$F^uF`x>Fa_m<#/
F^uF`x>Fd_n7$Ff_n7&Q>Thanh~lap~phuong~trinh~tu~sk8F$F:-Fa_n6$<#Ff^blFc]yFa_m>Fg
\lFfbbl-Fham6#/F_^blFhc_lC+>F^u-F^``l6%F[dblFbuFin>F1-Fdcq6#-F^hp6#F]ebl>F1F^db
l>Fc]y-Fh\`l6%7#-FgoFhgblFbuFin>F`xFc_bl>Fc]y-Fa_n6$<#-F_^o6$/&F]hblF_foF\`blF]
`bl<#/F[dblF^u@'3F`ebl/Fh^oFdeblC$>Fa_mF`u?(Fg`mFLFLFdeblFb]n>Fa_mFieblF_a\l>Fa
_mF`fbl>Fa_mFcfbl>Fd_n7$Ff_n7&Q>Thanh~lap~phuong~trinh~tu~sk9F$F:FifblFa_m>Fg\l
Ffbbl-Fham6#/F_^blFce_lC/>F1Fgcbl>F1F^dbl>F^u-F16#-Fgo6#Fadbl>F1Fegbl>F1F^dbl>F
`x-F16#-Fgo6#F[hbl@'F[iblC$>Fa_mF`u?(Fg`mFLFLFdeblFb]n>Fa_mFieblF_a\l>Fa_mF`fbl
>Fa_mFcfbl>F^u<$FddblF^hbl>F^u7#Ff]x>Fc]y-Fh\`l6%F^uFbuFin>Fc]y<#-F_^o6$/F]fblF
\`blF]`bl>Fd_n7$Ff_n7&Q?Thanh~lap~phuong~trinh~tu~sk10F$F:FifblFa_m>Fg\lFfbbl-F
ham6#/F_^blFeg_lC0>F^u7#-Fgo6#-FhanF\dbl>F`xF:>Fc]yF`u?&FhhlF^uFb]nC&>F1-Fdcq6#
-F^hp6#Fhhl>F1F^dbl>F`x7$F[`]l-F16#-Fgo6#-Fh\`l6%7#-FgoFc]clFbuFin>Fc]y-Fa_n6$F
c]y<#F^^cl>F^u<#-F_^o6$/&F^uFc^oFb^o/Fe`n;FLFdebl>F^u-Fijm6$F^uFf^bl>F`xF[b\l>F
^uFfa\l@'F_eblC$>Fa_mF`u?(Fg`mFLFLFdeblFb]n>Fa_mFieblF_a\l>Fa_mF`fbl>Fa_mFcfbl>
F^u7#Fe_bl>Fc]yFf[cl>Fc]yFi[cl>Fd_n7$Ff_n7&Q?Thanh~lap~phuong~trinh~tu~sk11F$F:
FifblFa_m>Fg\lFfbbl-Fham6#/F_^blF`\`lC(>Fbbm&Ff^blFfr>FehlF`u?&Fg`m&Ff^blFd[nFb
]n@%3-F]bn6$Fg`mF_bn/-Fgo6$FOFg`mFcbnC$>Fdhl-F^``l6%&-FgoF_foFfrFbuFin@&/&Feacl
FizFhen>Fehl-Fa_n6$Fehl<#/Fg`m&FdhlFfr/FhaclF^fn>Fehl-Fa_n6$Fehl<#/Fg`m&FdhlFiz
>Fehl-Fa_n6$Fehl<#/Fg`m-F^``l6%Fg`mFbuFin>Fa_m<#-Fijm6$FehlFe`cl>Fd_n7$Ff_n7&Q?
~Thanh~lap~phuong~trinh~tu~sk3F$F:<$Fe`cl-Fgo6#FehlFa_m>Fg\lFfbbl@$Fg`oC$>Fbbm-
Fhr6$f*F[sF$F\sF$-F^o6#-F]y6$F_s;FL,&-Fby6#F_sFLFa_alFLF$F$F$-F[i^lFc]l@$3/-F`r
F^goFL5/-F^hp6#&FbbmFfrF_`t/F^eclF_hp>Fg\l-F^hl6$Fa]lFg\l-Fje_l6#Fghl@$3-Fegp6$
FghlF__n/FhdvFLOF$@$/Fe]lF^bvC$>Fg\lFceclFeecl@$/FfhlFLOF$F$F$6.F\h^lF^uF^h^lFg
`mFjfxFbbmFfh^lF[i^lFgh^lFh\`lF]h^lF`x6#Fbr>F1Fas>FinF]^w@$-Fham6#/FinF[_^lC$>F
1&F]cnFfr>FinF_`t>Fg`mF:>FbbmF:>F^uF`u-Fh[p6#Q1bat~dau~tim~kiemF$Fhg\lFjfp-Fhhl
F$-Fje_lF$-Fc]yF$-F[h_lF$-Fh[p6$Q&-----F$Fg`m>Fe]lF:?&Fa]lF^uFb]n@%5-F]bn6$Fa]l
Fgdn-F]bn6$Fa]lF_bn>Fe]l7$F_]mFa]l>Fe]l7$Fa]lF_]m>F^uFe]l>Fa_m-F^enF^]o>F<-F`^w
6$F1F^u@%-F]bn6$Fa_mFi]q?&Fg\lFa_mFb]nC$-FghlFchq@$4F]inFibq-Fghl6$Fa_mF1F$6(F
\_lFjbrF__nFcjmF]inFd_nF$6#FLFg\rt+Fhju6#%#fnGF$F$?&F1F[blFb]n@$33/F`jyFejn/Fib
u-F`r6#F`jn-Fjgs6$FjaqF`jn@%/Fiep<#F[iwO7%F_hqFejnF`jnO7%F_hqF`jyFjaqF$F$F$6#FL
%%addVGt+6$%"VGFjg^lF$F$F$C$>Fas-Fa_n6$Fas<#FggpOFasF$F$F$6#Fbr%-Deduce_From3Gt
+6#F\is6$FgboFe`nF$F$C%>F1Fa_t@%4-F_^n6$F1FbjmC%>Fbjm7$F`jmF1>F__nF_jt>Fd_n7$Ff
_n7&F\\qF:F\btFjbn?(FinFLFLFgjpFb]n@$3/FhjtF\\qFjjt>F][uF^[u>F]inFb]nF$Fa[uF$6#
FL%*get_ParamGt+F$F$F$F$O7#-Fgo6#F]irF$Fh]dlF$6#FO%+xuly_ParamGt+6#%'SParamGFc^
oF$F$?&F1FasFb]n>F]ir-Fa_n6$F]ir<#F]oF$Fh]dlF$6#FL%,xuly_ObjectGt+6#%(SObjectG6
'Fe`nFhtFg^l%%kieuGFijvF$F$?&F1FasFb]nC$>Fin-FR6$FcxF1@$2FOFinC'>F<7#-F^o6#-F]y
6$F1;FL,&FinFLF_]lFL>Fa]lFhdo>Fg\l-F[o6$-F^o6#-F]y6$F1;F][^l-FbyF_oF`o>Fjbr7$Fe
erF`^l>F_er7$Faer-Fb^l6$Fg\lFa]lF$F_]vF$6#FL%(ptdthsgGt+6$FhtFijyF$F$F$O/,**&Fa
sFLFhenFLFLF^fnF_]l*&FasFLF^[wFLF_]lFa[wFLFOF$F$F$6#Fbr%1Replace_AttrNameGt+F$F
$F$F$F$F$F$F$6#FO%.Replace_UnifyGt+F]_yF$F$F$F$F$F$F$6#FL%-Has_FunctionGt+Fi`mF
c^oF$F$C$?&F1FasFb]n@$Fi]]lF\`qF^`qF$F$F$6#FLFadqt+6#'FgipF\hq6%Fe`nFhtFg`qF$F$
C%>F<F`u?&F1FasFb]nC$>FinFe]n@$Fi]n@$4-F_^n6$F1Fg^nC&>Fg^nFh^n>F__nF_jt>F<-Fa_n
6$F<Fjbn>F]inFb]nOF<F$6%FcjmF]inF__nF$6#FL%.IsEqual_UnifyGt+FabyF$F$F$F$F$F$F$6
#FbrFf]nt+Ff_x6$F[isFe`nF$F$C$@.F\`y@&333/FaeqFbr5-Fban6$F`ctFjbr3-FhdrFa]\l-Fj
gs6$7#-FgoFa]\lFjbr-F]bn6$F^gqF`o-Fban6$-F_iqFdgqF_erOFL2FLFaeqC%>F1Fas?(FinFbr
FLFaeqFb]n@+-Fban6%FacyF^ixFcdw>&F1Far-F_iq6#&7$FaerFigrFgdw3-Fhdr6#Facy-Fjgs6$
7#-FgoFbfdlFjbr>F[fdl-F_iqFbfdl-FgaqFbfdl>F[fdl&-F^hpFbfdlFfr3-F]bn6$FacyF_bn/-
Fgo6$FOFacyFcbn>F[fdl-F_iq6#F\gdl>F[fdlFdjy@$-F_jqF_oOFf^m-F[`qFgimOFbr3Fgfy-F[
`q6#Fa_t@)-F[`qF`^tOF`\n-FgaqF`^tOFbgs4-Fe_q6#-FhanF`^tOFe[nOFe\n3Fgfy5-Fe_q6#-
FhanF^hdlFehdlOFe\nFfaqOFgin3Fgfy-FgaqF^hdl@'FbhdlOFih\l45Fehdl-FjadlFfhdlOF[cp
OF\^nOFOF$6&FjbrF_erF]crFggrF$6#FL%*get_HyposGt+F$F$F$F$O7$F\]sFc_sF$F^fsF$6#FO
%)tlptdssdGt+6$%#d1G%#d2G6&%#a1GF]c`l%#a2GF^c`lF$F$C(>F1Ff]`l>F<Fi[z>FinFi]`l>F
g\lF]\z@$3-F]bn6$F1Fhjl-F]bn6$FinFhjlO-Fijm6$<$/F1F</FinFg\lFas@$3-F]bn6$F<Fhjl
-F]bn6$Fg\lFhjlO-Fijm6$<$/F<F1/Fg\lFinFggpF$F$F$6#Fbr%(ptdvgdtGt+F`gwF$F$F$O/,&
*&F]\zFLF_[wFLF_]l*&Fi[zFLFb[wFLFLFOF$F$F$6#FbrF\jvt+6#'%)filenameGF`o6@%(keywo
rdGFag^l%&AttrOG%)typeAttrG%+ConstraintG%)PropertyG%*CRelationGF[fq%&BaseOG%-Co
nstructProG%'DeterOG%*InsideNetG%.ConstructRelaG%%FuncGF[gzF6F4F5Ff`nFifl%)Read
nameGF[gl%.ReadvariablesG%2ReadConstructRelaG%0ReadconstraintsG%/Readproperties
G%1ReadConstructProG%.ReadrelationsG%*ReadrulesG%.ReadfunctionsGF$F$C4>Fh\`lt+F
$F$F$F$C->Fbu70Q-begin_objectF$Q+end_objectF$Q0begin_variablesF$Q.end_variables
F$Q2begin_constraintsF$Q0end_constraintsF$Q1begin_propertiesF$FbamQ<begin_compu
tation_relationsF$Q:end_computation_relationsF$Fh`lFcvQ:begin_construct_relatio
nsF$Q8end_construct_relationsF$>FduFco>FguF[hl>F^hlF:>F`hlF:>FbhlF:>FjdmF:>F`em
F:>FeemF:>F\fmF:>F]fmF:F$F$68Fe]elF1Fag^lFinF[^elFa_mFf]elF<Fg]elFg\lFh]elFa]lF
_^elFehlFi]elFe]lFj]elF^uF[fqF`xF`^elFfhl6#FO>Fje_lt+F$F\ilF$F$C%>F1F_il>FinFbi
l>FduFiilF$F$6&F4Fc]yFag^lFin6#FO>Fcb`lt+F$FfjlF$F$C'>Fa]lF:>Fe]lF:>FbuF_[m?(F$
FLFLF$3Fb[m/-FR6$Fb_elFbuFOC%>F1F_il@$Fj[mC'>FinF]\m>Fa]lFe\m>F<Fbil>Fg\lFj\m>F
e]lF^]m>FbuF_[m>FguFe]mF$F$6(F4Fc]yF6FhhlF[^elFa_m6#FO>F^``lt+F$6(FhtFe`nFgjl%%
lst1GF5FhjlF$F$C$>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$Fc_elFbuFOC%>F1F_il@$Fj[mC(>F<F]
\m>Fa]lFbil>Fe]l-F[o6$-F^oFg\mF`o>Fg\l7#-F_^o6$Fe]l/Fin;FLFhdo>Fgu7$F]bmF`^l>F^
hl7$Fa`vF]^l>FbuF_[mF$F$6*F4Fc]yF6FhhlFf]elF<Fg]elFg\l6#FO>F^]alt+F$F]_yF$F$C$>
FbuF_[m?(F$FLFLF$3Fb[m/-FR6$Fe_elFbuFOC%>F1Feam@$Fgam>FguF\bm>FbuF_[mF$F$6(F4Fc
]yF6FhhlFh]elFa]l6#FO>Fg`alt+F$F]_yF$F$C$>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$Fj_elFbuF
OC%>F1Feam@$Fgam>FguF\bm>FbuF_[mF$F$6(F4Fc]yF6FhhlF_^elFehl6#FO>8=t+F$F]_yF$F$C
$>FbuF_[m?(F$FLFLF$F^amC%>F1Feam@$Fgam>FguF\bm>FbuF_[mF$F$6(F4Fc]yF6FhhlFi]elFe
]l6#FO>8?t+F$6(%)leftnameGFap%(strlistGFhtFf`n%-ReadrelationGF$F$C'>Fe]lt+F$F$F
$F$C%>&FbuFfrFdu>FduFeu?(F$FLFLF$3F[v/-FR6$Q-end_relationF$FduFOC&>F^hl-F[o6$-F
e`pF[xF`o>F`hlFiw@$-Fban6%F^hlFbhl.Fjdm@%/F^hlQ%expfF$>&FbuF]jal-F^o6#F`hl>Fhie
lF`hl>FduFeuF$F$60Ff`nFa]lF4FbuF6FduFjgelF1FapFinF[helF<FhtFg\l6#FO>Fa]l7)FcoFL
F`uFLF`u/FLFLFO>F<7)FcoQ%flagF$Q#MfF$Q#rfF$Q#vfF$FfielQ%costF$>FbuF_[m?(F$FLFLF
$3Fb[m/-FR6$Fh_elFbuFOC$@$2FO-FR6$Q/begin_relationF$FbuC$Ffhp>Fgu7$F]bmFa]l>Fbu
F_[mF$F$6(F4Fc]yF6FhhlFj]elF^u6#FO>8@t+F$6#F[tF$F$C$>F1t+F$6+FatFbtFctFdtFetFft
FgtFhtF\tF$F$C->F1Fco>FinF:>F<F:>F^uF_u>Fa_mFco>FbuF_[m?(F$FLFLF$33Fb[m/-FR6$F_
vFbuFO/-FR6$FcvFbuFO>FbuF_[m@$2FOFa]flFgv>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$FawFbuFOC
$@%2FO-FR6$FgwFbu>F1-Fjw6#FeamC$>F`xF_il@*2FO-FR6$FhxFbuC&>F[y-F]y6$Fbu;F`yFfil
>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$FiyFbuFOC$>F[y-FA6$F[yFbu>FbuF_[m>F[yF`z2FO-FR6$Fe
zFbuC&>FhzF\_fl>FbuF_[m?(F$FLFLF$3Fb[m/-FR6$F`[lFbuFOC$>Fhz-FA6$FhzFbu>FbuF_[m>
FhzFg[l2FO-FR6$F\\lFbu>Fa_m-F^o6#-F]y6$Fbu;,&F_ilFLFLFLFfilFd\lC'>Fg\l7#-F^o6#-
F]y6$FbuF]]l>Fa]lFb]l>Fe]l-F[o6$-F^o6#F\_flF`o>FinF[^l>F<F_^l>FbuF_[m@$Ff^l>Fgu
7$F]bm7'F1FinF<F^uFa_mF$F$6(F4FbuF6FduF[fqFgu6#FO?(F$FLFLF$3Fb[mF`]flFigmF$F$6(
F4Fc]yF6FhhlF[fqF`x6#FO>8At+F$F]_yF$F$C$>FbuF_[m?(F$FLFLF$Fa^sC%>F1Feam@$Fgam>F
guF\bm>FbuF_[mF$F$6(F4Fc]yF6FhhlF`^elFfhl6#FO-Fh\`lF$>FhhlFabs>Fc]y-FIFc]cl?(F$
FLFLF$30Fc]yFO/-FR6$F`_elFc]yFO>Fc]yF`dfl?(F$FLFLF$3Fcdfl/-FR6$Fa_elFc]yFOC$@22
FOFedflC%Fggcl-Fcb`lF$F`dm2FO-FR6$Fb_elFc]y-F^``lF$2FO-FR6$Fd_elFc]y-F^]alF$2FO
-FR6$Fi_elFc]y-Fg`alF$2FO-FR6$Ff_elFc]y-FjfelF$2FO-FR6$Fg_elFc]y-FggelF$2FO-FR6
$Fh`lFc]y-F\\flF$2FO-FR6$FiblFc]y-FacflF$>Fc]yF`dfl-F\pFc]cl>Fghl7+FinFa_m7$F<F
g\lFa]lFehlFe]lF^uF`xFfhl-FhvFfeclF$F$F$6#FLFagpt+F$F]\dlF$F$C$?&F1Fc[nFb]n@$4-
Fban6$F1F]bpC$-F[\dlF_o>F]bpF^bpOFehsF$6$FcjmF]bpF$6#FO%)tlptdvgdGt+FdjdlFgjdlF
$F$C(>F1Ff]`l>F<Fi[z>FinFi]`l>Fg\lF]\z@$F`[elO-Fijm6$<$Fg^`l/Fin,$F<F_]lFas@$F
\\elO-Fijm6$<$/F<Fin/Fg\l,$F1F_]lFggpF$F$F$6#FbrF_bst+F$F$F$F$C/>F]irF`u>FjbrF:
>F_erF:>F]crF:>FggrF:>Fj^rF`u>Fcjm7-F:F:F:F:F:F:F:F:F:F:F:>F\fsF`u>FcasF:>Fd_nF
:>F`crF:>F^drF:>F__sF`uF$6/F\fsFcasFjbrF_erFj^rFcjmF]crFggrFd_nF]irF`crF^drF__s
F$6#FO%0Determine_ParamGt+6#%$ParG6,FgipF_h_lF_i^l%)find_objG%*call_funcGFdh^lF
f_`l%(set_eqsG%*test_goalGFiflF$F$C.>Fg\lt+6#%$parG6$Fcin%%objsGF$F$?&F1Fc[nFb]
n@$-Fban6$Fas-FhanFh\rC$@$/-F^hp6#FjwF[_^lOF[i_lOF[bpF$F$F$6#FL>Fa]lt+Fhju6#%&f
nameGF$F$C%>F1-FdcqFf`u>F1F^dblO-F16#-Fgo6#F_cqF$F$F$6#FL>F^ut+F]_yF^_yF$F$@)Fa
_yOF`uFjj`lOF\btF[`yC%>F1F`u?&FinFasFb]n>F1Fe[alOF1C$>F1F[\alOF1F$F$6$Ff_`lF^u6
#FL>F`xt+6$F`^]lFa^]l6$FealFj`alF$F$C$>FinF`u@%0FaeqFLC$?(F1FLFLFaeqFb]n@$0-Fbu
6#/F\azFb]tF`u>Fin-Fa_n6$Fin<#Fc_glOFinO<#F^eyF$F$Fc^gl6#Fbr>Fe]lt+6#%&otempG6)
F]gsF`^]lFa^]lFj`alF]h^lFealF[falF$F$?&F1F`gsFb]n@$-Fban6$FasF\d_lC)>Fin-F^enF
\b_l>F<-FbuFh\r>Fg\l-FduF^dy>Fa]l-FguFc]l>Fd_n7$Ff_n7&Q-Ap~dung~sk~9F$7#F1F\d_l
Fg\l@$/Fb]lFaa_lC%>F^u-%&solveGFi`dl>Fd_n7$Ff_n7&Q(Giai~ptF$F:Fg\lF^uOF^u>F^hl-
Fa_nFhg_lF$F$6*Fa[glFa]lFb[glF`xFf_`lF^uF_i^lF<6#FL>Fa_mt+6%Fh[glF_`glF[is6%Fea
lFf`n%"oGF$F$C$?(F1FLFL-F`r6#F`fxFb]n@$/Fas-Fe`p6#F`a`lC'-F`]q6#QK~B|[yi~to|\yn
~gi&#7843;i~&#273;&#432;&#7907;c.F$-F`]q6$Q@|+~***K&#7871;t~qu&#7843;~l|[y:~%aF
$F`a`l-F`]q6$QJ|+~*****~L&#7901;i~gi&#7843;i~l|[y:~*****|+%aF$Fd_n?(FinFLFL-F`r
Fb[nFb]n@$/Fggp-Fe`p6#&Fc[nFar>F_dgl-Fijm6$F`a`lF_dglOFb]nOF%F$F$F$6#Fe[n>Fin-F
g\lFgim>F<F`u>Fd_nF:>F1-Fe]lFar@$-Fa_m6%FasFinF1OF$OF<F$Fc_qF$6#FL%$tvhGt+6%Fij
yFjjy%"CGF$F$F$O/,&*&,&F`ctFL&F`fxFfrF_]lFL,&F^[wFLF[fglF_]lFLFL*&,&F^gqFL&F`fx
FizF_]lFL,&Fa[wFLF_fglF_]lFLFLFOF$F$F$6#Fe[n%+StructNameGt+Fi`mF$F$F$C%@$4FhbwO
Fas@$-Fban6%FasFfdwFcdwO-Fcbn6$Fadw-F^o6#&F]dwFgdwOFasF$F$F$6#FL%%TestGt+Ff_x6'
FapFfboFdboFi`nFf`nF$F$C(@$F[`y?&Fa]lFasFb]n@$/-FcgglFg\mF%F^`q@$4FgfyF\`q>Fg\l
Fg[x@$0Fb]lFbrF\`q?&FinF[\nFb]nC$>F<Fgan@$33/FhdoFbr-%)Unify_inG6$Fg\lF</-Fb[o6
$<$FinFasFg\lF`uF^`qF\`qF$F$F$6#FLF^j]lt+Feip69%(HuongMTGFe`q%'uutienG%*kh_uuti
enG%)GoalTypeGFh`q%&ToHopGFf`qF[is%*FactTypesG%)FuncsAppG%+FuncStructG%(FuncNew
GFe`nFfalFd`qFgipFhtFg`q%$HMTGFjfxFh]tFi]tF$F$C+>F1t+6#%#MTGF$F$F$@)-Fham6#/Fas
FfhtO7$FfhtFi]q-Fham6#/FasFi]qO7#Fi]q-Fham6#/FasFc]\lO7$Fc]\lFi]qOF:F$F$F$6#FL>
Fh\`l-F16#-F^hp6$FasFL>Fg`m-F_]w6$7#F`jmFL>FbbmF:?&FinF[blFb]n@$3-Fban6$FerFh\`
l-Fjgs6$F]ezFg`m>Fbbm7$-FgoF^goFin>FehlF`u>Fcb`lF`u?&FinFbbmFb]nC%>F`x-FdcqFar@
%/Ff^zFjjcl>F^u-F\ix6%F]ezFbjmFL>F^u-F\ix6$F]ezFbjm?(Fe]lFLFLFdeblFb]nC&@$-Fban
6$7$Fin&F^uF`]mFjcqF`dm>Fhhl-F^en6#F[^hl>Fehl-Fgcq6%F`xF[^hlFhhl@$0FehlF`uC&>F[
i^l-Fadq6#-F[o6$FehlF\hq?&FfhlF[^hlFb]n@%5/-F^hp6#FfhlF_`t/F^_hlF_hpC$>F^``l-F^
o6#-FA6$-F[o6$FfhlF`oFi`t>Fcb`l-Fa_n6$Fcb`l<#/F^``l-F^enF__hl>Fcb`l-Fa_n6$Fcb`l
<#/FfhlF^`hl>Fd_n7$Ff_n7&Q-Deduce_FuncsF$FghnFcb`lF[i^l>Fjcq-Fa_n6$Fjcq<#Fj]hlO
FehsF$6)Fgb]lFjbrF_erFjcqFcaqF`crFd_nF$6#FLF\ixt+6$'FefxF\hq%%FactG6*%'TH_ObjGF
ijvFe`nFfiglFht%&OtempGFcin%-TestCombinatGF$F$C*>F`xt+6$F`fvFffxFfguF$F$C$?(F1F
LFLF^]tFb]n@$/<#-Fgo6#Fb]tF^ayOFb]nOF%F$F$F$6#Fbr>FinFaeq>Fe]lF:?&F^uFggpFb]n@$
-Fban6$-F^hp6$F^uFLFas>Fe]l7$F_]mF^u>F1-F]gv6$Fe]lFin>Fg\lF:?(F<FLFLFehqFb]n@$3
/Fas-F_]w6$FihqFL/-F`rF`iq-F`r6#<#-FgoF`iq@%Faf^l@$4-F`x6$FihqFg\l>Fg\l7$F]^lFi
hq>Fg\lFedhlOFg\lF$F$F$6#Fbr%*xuly_GoalGt+6#%&SGoalG6(F5Fj`mF^brFhtFe`nFiarF$F$
C(>Fe]lt+F]brF_brF$F$C$>F1Fbbr?&FinF1Fb]n@)FccrC&@$FfcrF`dm>F`crFjcr>F^drF_dr?&
F<FcdrFb]nFddrFfdrC%@$FfcrF`dm>F_erF`er>FjbrFderFgerC'@$FfcrF`dm>F_erF^gr>FjbrF
agr>F]crFcgr>FggrFhgrC%@$FfcrF`dm>F]crFcgr>FggrFhgrF$F$6$FiarFe]l6#FL>F1F:?&Fa]
lFasFb]n>F17$F]cnF[del>F<F`u?&FinF1Fb]nC$>Fg\lFj`s@$F\asC$>FcasFfas>F<Fjas-Fe]l
FJF$6)FcasF`crF^drFjbrF_erF]crFggrF$6#FLF$
